environments:
  default:
    values:
    - domain: "bazarr.{{ .Values.shared.domain }}"
    - middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"

---

releases:
- name: bazarr
  namespace: media
  chart: k8s-at-home/bazarr
  values:
    - persistence:
        config:
          enabled: true
          type: hostPath
          hostPath: /homelab/bazarr
          mountPath: /config
        media:
          enabled: true
          type: hostPath
          hostPath: /storage
    - env:
        TZ: America/Toronto
    - ../../ingress.yaml.gotmpl
