environments:
  default:
    values:
    - domain: "jackett.{{ .Values.shared.domain }}"
    - middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"

---

releases:
- name: jackett
  namespace: media
  chart: k8s-at-home/jackett
  values:
    - persistence:
        config:
          enabled: true
          type: hostPath
          hostPath: /homelab/jackett
          mountPath: /config
    - env:
        TZ: America/Toronto
    - ../../ingress.yaml.gotmpl
