environments:
  default:
    values:
    - domain: "plex.{{ .Values.shared.domain }}"

---

releases:
- name: plex
  namespace: media
  chart: k8s-at-home/plex
  values:
    - persistence:
        config:
          enabled: true
          type: hostPath
          hostPath: /homelab/plex/config
        transcode:
          enabled: true
          type: hostPath
          hostPath: /homelab/plex/transcode
        media:
          enabled: true
          type: hostPath
          hostPath: /storage
          mountPath: /media
    - env:
        TZ: America/Toronto
    - ../../ingress.yaml.gotmpl
