environments:
  default:
    values:
    - domain: "sonarr.{{ .Values.shared.domain }}"
    - middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"

---

releases:
- name: sonarr
  namespace: media
  chart: k8s-at-home/sonarr
  values:
  - ../../ingress.yaml.gotmpl
  - persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /homelab/sonarr
        mountPath: /config
      media:
        enabled: true
        type: hostPath
        hostPath: /storage/TV-shows
        mountPath: /tv
      downloads:
        enabled: true
        type: hostPath
        hostPath: /homelab/transmission/completed
        mountPath: /downloads
  - env:
      TZ: America/Toronto
