apiVersion: v1
kind: Secret
metadata:
    name: github-pat
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EOLSz0eZzxcZb5Qz+d1LfdSwZVKfcs/L2ofe+7bq8ruVPqVvz3SMZw==,iv:bto8M6QaueUMcAJ04Qjv9YGxLIQl655INCE6O+pglPM=,tag:BqsGuNB6QRUA9Hhy39nP6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-10T19:40:20Z"
    mac: ENC[AES256_GCM,data:Dc0XqVwCXZ7zuoVOMIN7NUoeMAc+i6WrML+r4gBpB/RSw6K5xQoamxtXBjwS7qSJofJB1VB9G1/SzNDQ71uKU9aXbV0salBpi+Sp0my8/kKHfuFfA1cqOWvb6uDsORa7DuEJwLCRIuoilXfBQJPBzUFesUXe/j3umpKCYzNq1js=,iv:odulqchdf/goIHE0Q+Y7Ma+aWg+V6nOD0mLhwSSMfDg=,tag:Xl0jCF8A4LigtHKzl8w8Ig==,type:str]
    pgp:
        - created_at: "2022-08-10T19:40:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf+NgBPHFIunQqZA5MyP5/HV1Ic2gi48gK0mpIO0k5R6Odb
            4/uyUTtw/2LpXBgHuNfWvMUvPEn1rowz6rdnrfIVU/bYyjdLXrboUOm0FR/+hgET
            HAwzTVI6FsXlvjBdvld9exjfFNi7+SSpMeYEiio//MBU6s4fk6jQMnq1G91ebcI5
            7fig8z3qCbltiLpT8p5bUU9mSE6FKCk3RzoFHaF4hlzR4eD4vc2XpwZA5T4k1Y9l
            4PZf85MHnbhimjDlbXFZZ9+kX6bs8t1fZOKqnFflAUPKEEG2+aQFyVy0wIsSv1z5
            kJ3HVQN5bnY0gGiFJOvPZQ0oA647LjH9RK6I/1uwVdJeAUxZNOgJbq2hYeds18P3
            nfta401NC531l99czQYfQkQDlsy5JOiQ3dtLuAgHwVjKSnT1O7AX/Oj96zUr0PnS
            pAPA980x/fWPsYpND08+zaYWzJ6Ei/GbZfapGgFATg==
            =HSeB
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2022-08-10T19:40:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ/9EbdphX9erjjT6oIa/+FwS6aVmALPA5SZVYe2gc66PW7+
            E202VBoXcMjhA/7OoLWpcJlJFFz0FqOoWOxEkl7EsYfzto4feD2mQmkbU7GLioQr
            abtpLo6YoiV0YWhlyW89O2KsqgAvmZQ3rrRzlvR1BoZj1Fc3zaqfYKT2Ygu50uXN
            ekUD8iaT9lUhJcD0QtLs1dvxQ5T8g1O6vUGotMxiM/v+YvFELKnUXZkFVsxIQGy0
            Qijzjkabjrm2xi4A0nTyy1Z3TtMheSmH9BGmo6y7etZGCV8dKoSfJYkIvT9znMeq
            6xFpjof14fN+seM5PRyj3N8+vzrlrECBidbDnp/UwVrWvEMnZSgGGlDRzXkdTqAo
            4ds8OgOAp91KFMN+FHqu26knU4uvLShs5I4SW7oHTWCdJdgcEq3Z12Bidg+TXP0Z
            iA28WwoZq2MnQSpx0aNHdKhtbLy8DDrGVcpGFYW9JE2LttF0FGQzSP7T1Oi4gAsE
            gGxf3GBp3DTy3DFXf0QQ/JNMcS7fhLuY5mpc+6swoP512nws4yq0R8cBYe7IGHad
            j34BaNCJwPwYH5ci5LseFXaxdthJ7MYXn9D6zocjqNC0M9MbKsa8uoB6uZsjK6s7
            qu/oVlorGbuyPh2RSUSF/alIRC5Umnv5ifts9MljoTh7Mt9NHzQuktGJW9+cy3/S
            XgEiiiepTujZjtNQ/ZR/h88/twQoDh+UK6vdKkYxHV7qoA5i1/eQ20zKQeLI9lFE
            cRaLkjem9/j0HVjkY5LdoS2GLt1CRrVxgH75wN0OG4ATXmvVgKlrvQ4OIjSB7Ew=
            =wBg/
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2022-08-10T19:40:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/+LdC+NiwR/zXHI8D/7uGSVEk25wC0QwrfqUuUM0m+H/qn
            92k4mcW9BrZr2E4gMaM9HJwifwUKJIgyanaSdpg1SHzShkA56UwfuceKdP5Xc7sI
            EwA3+hCax5ANQ1cguds9iVlrZSqmxDRSSdtm7q8o8MaMrzZ4FubYmKYdtUtqvcVT
            PRiecsirC0QDviLNSCGe5z8Hp3nDDUiel9kzxRThuibQ0twTeVdlnkuqBm444XhN
            wjPWoabCjk/yQcJZoldRjJi+LBSizMVxIgsrvrTh/yAfDEXw/tqYRYgbeBAwm9gI
            qERy9a3jViD1hYV2yiEHMI/d0xhZrYEs9SN0fQw9bzerCVeArUpCzalIrXVhIx8R
            oTwLRNRCoAxg06R2r9B4B/cx8LwWZDBDKW58xd9AMNMOUNXuSBoxrYjky+DFcq+5
            k0IJq2JvklYIfMhGx9L2ZxH0coJrs9HPXnIct2IMQYtb+XyUJM63E/jwTMShCrvb
            QTalrICbuE1X12BEjcUfWXPos3jOXJpG+B5Fc1b8vpnfMC/JTwFzDB9lm613q7lq
            GW0aSDmwpJkVg5J4yygLjI554/H8xGwqhGfUn+pm/wJm4F2WVLuOthldwGoltD67
            j6yjYYqCOpOH7uJ5bV4Nof64a6/W6sy4oBPfFDEstYS/GZEyc6MVyO9f0bZ1H1vS
            XgGigz9Zh+H+We5aII6h89LjXrTCHXCa2wbXT4bVPuPSViPHQIaCnOFshjK3fPE1
            AoGQo33c+mXr+JhXsJQinzglgaTlFWXYTA9DZ7lwWjb1QFhb5EULh1EHxwTopuI=
            =hTwS
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
