apiVersion: v1
kind: Secret
metadata:
    name: github-pat
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EOLSz0eZzxcZb5Qz+d1LfdSwZVKfcs/L2ofe+7bq8ruVPqVvz3SMZw==,iv:bto8M6QaueUMcAJ04Qjv9YGxLIQl655INCE6O+pglPM=,tag:BqsGuNB6QRUA9Hhy39nP6A==,type:str]
sops:
    lastmodified: "2022-08-10T19:40:20Z"
    mac: ENC[AES256_GCM,data:Dc0XqVwCXZ7zuoVOMIN7NUoeMAc+i6WrML+r4gBpB/RSw6K5xQoamxtXBjwS7qSJofJB1VB9G1/SzNDQ71uKU9aXbV0salBpi+Sp0my8/kKHfuFfA1cqOWvb6uDsORa7DuEJwLCRIuoilXfBQJPBzUFesUXe/j3umpKCYzNq1js=,iv:odulqchdf/goIHE0Q+Y7Ma+aWg+V6nOD0mLhwSSMfDg=,tag:Xl0jCF8A4LigtHKzl8w8Ig==,type:str]
    pgp:
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQgAlsIs9sCOTqnJ9W15lNAIflRYj/W3mqAATcj5NwuQ91Uy
            PKvIRMHjKwVGZlTlCVA9pbpHuRld3DvYsPtAwqj5FnsrTccBAyO0MytfJ4weTs+J
            HFtUUNgczeEM6R/Q5Qv1NvbIBenq53Lq7Fy5MGfjM14PWegqUPr+SnJz4bR3+f1j
            Rlq63ZZsjK+eYkm1Tx4wLeKRUF6ZhP3u5z22BQjXkRtWBog34IVZZQNWHyxl78Fu
            eLNzWexkNawaEF9nZywUfd/VH+udsn54rQsv3y6CtiXmH/2F4Nv7x5VN0UEwy5GI
            XKH/fsWA88bkcJ9ZIxhHxwHvyFoEO4DWQFjOZNcvdNJeAWeQ2XBJ2oyItLv/Fwcf
            qkjDYpLtFx7oF5fmFaPMpaU+jKJL0B+x37TLH/qpWqSmBrGqXlVacwMojTET2alq
            A3IeRYZijS0LZ0ZPR3jd50mXBS/dyrI4aEyvj64Pjw==
            =zZM+
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0ARAAssgSGMGYjcvKTNL6HGBVQ3r0CfBXNs43bat8Lw52iy6b
            X6WfQXVnUokaAZ1WRlQZ5pDa+8/dv7/SIiJod/bH1ot8MXCdINmWBW40wmv1MiJX
            xdP4c8EiQ+NwtsHTDsEM5BwjBue83xkKQ8Gd606eIMHTBazxsME14uEvDox9KQl6
            TMX5zpskscZrt4u3ATcBjdEHfrcuLClyGnGfhNx83CjL4hXo7goSxe9Nz7yxxCeZ
            Go66TroZObpDoI0M7E4Dt1OHONLqtu6NMizv69g+a769enkQ8zAD6bkJqmAQj6Kq
            voXDEQOzxsliDt8ywsLjXgwb5Wx+TE6xvI+bLOC55oVFaKqoXvGDqR0zKBBUigDq
            15LA712bRgCMJ0B1yqBfZTNRSBAzGNv/E5ZJNFmg3Hu6UnAcvIN4I3sRqfAEOIPb
            HQ4r159ct4rcVynvuIdLylVpUlc71s7/dCNNwIOTBOrywt882sWoXvg7KGK+DNgo
            PtQC7dw4YcX4XVznMCf7yJit0JE7Orrb6xTO/+DuTJu+rQJpTKp39x3XKo511P4L
            omKYUn4ezfxa09oxhkK/R3QcNMglMQ3W9V1DIy0rdj+tLVDklONhQfLLnvs/8fSA
            IqmrAF2k41TP6SHaRQ2P02fbixhQog+MbELiJ05QEBHU0xR7OCZiW1SBJu4TnqrS
            XgFO8f2BdoEGYEk3Hk32asE+ybZWK9+rILPLR6gqP3KoxM/mso09pzROoaQBxe9g
            b+BEcd88Aru/iiaB8fLcc5Q6B/v2eAH4grR/CqyXRFvLCEm1z9zLxREBG1SByos=
            =GLkv
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ//YlpGKox64w0Bew1poG7gq8cDchgbOYhP/E/6FHMn7hNO
            SzclSDfIxTO9RGYlZ6IiVUbFeN+/+PzL/XbOHsZw/K0pEiBFTWD3JlvLjEcXTubw
            QSujrKoKLC4Lvz8PP0FWW25Cavws4OLdwQwcdseO25CJ39TJNcEfjJQLKk9ztOCK
            3Dr76OSbttH4KdDqyJXvQrW+/adu/7GUliph0rsHBrZZniRIv88BHiBgQIpCDYrV
            qcn8yLXpoefn6oqp4jY7XP6OdzqLqL0n+cdElZWD6hpVjP+ucoJ0bCAL9eoyxqt2
            XdPNLr/y71xAh6y23uMz8fPSFD82QaCe+NMlnhKyG9l1CllZaexIxRJN4kJL9Pr8
            hx/kMzcrz7hWK8QPsilfyA2Xq3rZ6RRalbPDuPNzvGQmmSa5e4dWd5VDbfIfQZWQ
            go6rQOMmqMknv5PMejPycEUHUvjHGX5fzVikDvhr0YUqY69Lk4C/Venx4a+ll77K
            59lLeX3tmuhLPwOvnUEeoLNIAebtkD2aj5lRwA6rodXTiM/wyTADS/VkpiS2SODf
            zDPVRsSmphzMQnMGNnKjA7d/L2Chgobr/L2TKq/xNXdbskwUQwjV5H9v3HtxOROs
            YXpi9y4ep0c4fEIDftZ47r9e7ha9n5oSuGjunNVmgB0X9pgcfSPsutQlf6Y0nEbS
            XgHXbjHmzXlRKRKd25+kXCmYvpEwpBOxJoJ1XskduzC81tr2+uZroo3+q+miSunm
            k/8L0ucOArasZ78AGp1S2ecGflxBj+tag6rgX4jTrTVznfOQDSraKIvJG7phHUI=
            =gtoF
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdAC3l/oKEfrPiZLJC8Dy0lVwqhRxwyLB1puB/uO+RNgCow
            jrbxYCYHdFNKQ9/gghyT1ZdrUfdoM3aBi5mRAWQfKXAkVX8VI9O+jR1NbKNe9fx9
            0l4Bl3qQ2Epz4UWpiMktG8j8UcIw0V1m0aVyNvFWAF3lVb/kHQaG3nUeM0mabciH
            Ig2oInshI1C+Ek5+Mu7W5unNRbiiEhdBwpCN9iDpvJhvYZLfQEyUvfsmuDXNop+J
            =j4xF
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DrvgYWgvgiW4SAQdA97xuoCXzEH5lEmtTFO3R9t3KryWUE0fNzqZBTUcWFUow
            r6HIecf2caW1snToB8mKw5Geosy7/kdwID4sjAz2hQPeZbvbeXQf519qQ5w5p9QT
            0l4BrHtGv7raraVzVi33TxRn9ArAp2FqMlZ5+Izo/jAsL9TIT2Psc3h+bsRPUq56
            MabPWc1+NMv77KZ5+rVPiJh1hgMzqgz8i1RMy3jcYbdMGxq05our6SsIGcjkFfV6
            =xuZn
            -----END PGP MESSAGE-----
          fp: F75CA0B534439722B612D343FAB6BD4E290CA406
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
