---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/WolfeCub/home-ops
    targetRevision: argo
    path: ./kubernetes/argo/namespaces
    plugin:
      env:
        - name: SOPS_SECRET_FILE
          value: ../secret.sops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
# syncPolicy:
#   automated: {}
