---
configs:
  cmp:
    create: true
    plugins:
      sops-replacer-plugin-kustomize:
        allowConcurrency: true
        discover:
          find:
            command:
              - sh
              - "-c"
              - "[[ ! -z $ARGOCD_ENV_SOPS_SECRET_FILE ]] && find . -name 'kustomization.yaml' && find . -name '$ARGOCD_ENV_SOPS_SECRET_FILE'"
        generate:
          command:
            - bash
            - "-c"
            - |-
              kustomize build --enable-alpha-plugins . | argocd-secret-replacer sops -f "$ARGOCD_ENV_SOPS_SECRET_FILE"
        lockRepo: false
      sops-replacer-plugin-helm:
        allowConcurrency: true
        discover:
          find:
            command:
              - sh
              - "-c"
              - "[[ ! -z $ARGOCD_ENV_SOPS_SECRET_FILE ]] && find . -name 'Chart.yaml' && find . -name '$ARGOCD_ENV_SOPS_SECRET_FILE'"
        init:
          command:
            - bash
            - "-c"
            - helm dependency update
        generate:
          command:
            - bash
            - "-c"
            - |-
              helm template --include-crds --release-name "$ARGOCD_APP_NAME" --namespace "$ARGOCD_APP_NAMESPACE" --kube-version $KUBE_VERSION --api-versions $KUBE_API_VERSIONS . | argocd-secret-replacer sops -f "$ARGOCD_ENV_SOPS_SECRET_FILE"
        lockRepo: false

repoServer:
  volumes:
    - configMap:
        name: argocd-cmp-cm
      name: argocd-cmp-cm
    - name: tmp-sops-replacer-plugin
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age

  extraContainers:
    - name: sops-replacer-plugin-kustomize
      command: [/var/run/argocd/argocd-cmp-server]
      image: ghcr.io/mmalyska/argocd-secret-replacer:rolling@sha256:5a0f25fd26b6dbc19d700ba0734d8b82e8b294e2c490a84df1aee307a8e1a607
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 16Mi
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /sops-age/key
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-sops-replacer-plugin
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: argocd-cmp-cm
          subPath: sops-replacer-plugin-kustomize.yaml
        - mountPath: /sops-age/key
          name: sops-age
          subPath: age.agekey

    - name: sops-replacer-plugin-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: ghcr.io/mmalyska/argocd-secret-replacer:rolling@sha256:5a0f25fd26b6dbc19d700ba0734d8b82e8b294e2c490a84df1aee307a8e1a607
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 16Mi
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /sops-age/key
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-sops-replacer-plugin
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: argocd-cmp-cm
          subPath: sops-replacer-plugin-helm.yaml
        - name: helm-working-dir
          mountPath: /helm-working-dir
        - mountPath: /sops-age/key
          name: sops-age
          subPath: age.agekey
