apiVersion: v1
stringData:
    docker_host_ip: ENC[AES256_GCM,data:GVMNpEuZ4ujPQEijmg==,iv:34PwtffHaSFlxVKwg9t9qMGhf3rrzS7UD2R8tHLJYXk=,tag:oPZ/kngcXrPbZ8KjxjT3+w==,type:str]
    domain: ENC[AES256_GCM,data:LsIdv9mwz9pjNxVk,iv:RXJmfVHwnEWDioUsRp/guQaHI9BpC53/Z1LqTM2EVe0=,tag:yQFcjySdll36+SCz/U+sMw==,type:str]
    email: ENC[AES256_GCM,data:mo+VnvKjqaxfQnb/mh9H9b/DsOOZRw==,iv:P4f3fdnoQXxOg3uhCwy5TuFqBsFlM9I1mzuY5Mv5Kss=,tag:sB+9vuuaqupHygEvjAQvTw==,type:str]
    network_subnet: ENC[AES256_GCM,data:3fyP1cGeRdvVujzjNU0=,iv:ElU0QjsFgd86OFfC2trnUN8K1GNnnEy1I+UOAx/0OzI=,tag:KsqrGgxhfflge0v+bp4E3A==,type:str]
    storage_host_ip: ENC[AES256_GCM,data:Z+Ys9YssI+nf5nN6Uw==,iv:91GRpe95R2LwO38V4jn7LLKIEBA8a1aHFKCf65uXS74=,tag:4yUP3i6bubBZuJnZZ2O/nQ==,type:str]
    traefik_basic_auth_credentials_hash: ENC[AES256_GCM,data:5vASFWu9ayAsaAVc3IC5gSVZvsgt50WUS8VyAW/afDskdOsquCb88SbzZniz68thlhRtaIHNXkOh9txLGJ03XWst,iv:nor3qwl4730OF/M2797rlN5psSXgDbA5jsBZEKLYiUo=,tag:upF1IP0vF5Jtlr2ca0CzLg==,type:str]
    #ENC[AES256_GCM,data:Mtz92cVjkX6G60lkLF2VS6pOfpXmvDzHffQOYZk4cO0/AYNSl88BMaiP8MGawZp1bDs5jYmn7A==,iv:xLyDlV0coA2zFB3XQ1lsq28JvrgAuQnz2CYLslTAdiU=,tag:MFWCgAuFQDnvznPL3G1/yg==,type:comment]
    authelia_jwt_secret: ENC[AES256_GCM,data:JHxLvr+AjSalJbj66O/4Nl5hAD4PMyTJyUE3cMbka8Q=,iv:51Wx6GA5nECsg2ojslpXaL/Jk5rkSKcvxZXVNYfcUM4=,tag:IbrVcp6MPYcJc+YHBTy2qg==,type:str]
    authelia_smtp_email: ENC[AES256_GCM,data:gEckkVZvyAzmlQlTHHtaAWEDXDM6evnYZ64=,iv:Cva2vru73Zh+Fq7we66dkLRDOEDrCELxSpw0iVKnngA=,tag:hgm/djIOi7raTxWOGqy61Q==,type:str]
    authelia_smtp_password: ENC[AES256_GCM,data:g8ZOKEEAqM76l1KQ5jdF73ApSdk=,iv:DfjczKiN0v9fuAGx74gZXnKWgehCf1xahiPIU2+KXAI=,tag:ZvtJ8QYECAjTLrbtJ2OV4Q==,type:str]
    authelia_smtp_server: ENC[AES256_GCM,data:1rsP4SUMOTD7xO4kcw==,iv:WmqbEzKqNg5Er/JGhF9X7K0dmqYeD4Jdsp75XDQne8o=,tag:mKlXyJgQk+xcdWV7zoEVkg==,type:str]
    authelia_primary_email: ENC[AES256_GCM,data:fwnZD8J/SlxYEaBA9hB/I7y7NE7fuQ==,iv:GB8AbDCifMfL6UCYEYTSDMEVxFJzd+1UT+vSvQ3QSPg=,tag:BtQAbHwMV3lnHVnOKLJadQ==,type:str]
    authelia_primary_password_hash: ENC[AES256_GCM,data:p6BMlchcRYWTK/60ckOrv6ZsS6JMOV4PZJ7JcXHLW4VwYBGTbPUs1PeKqy/f+0BmnOVg1B4exgrmWL9ayw2q8bnNvZvpjKxIjR7fFeF19+LvsEDlSzMvsVd1bkHnCBRuSA==,iv:xbIHHsAbpkdEYNUbxserMnUvN2W4Dzmkg96WiCTQmag=,tag:7/jmCiDIpemLaxQy0zwfhg==,type:str]
    authelia_primary_username: ENC[AES256_GCM,data:Gj5v7Uc=,iv:xkQOxjnVFzCYciAxfK/eMnVe1mYbeved55LxTsTr9jI=,tag:Esg01NMBwb0fT0A+cVQDbg==,type:str]
    authelia_secondary_email: ENC[AES256_GCM,data:KaYcxYN7ZcAAyV3iHeXqxA==,iv:fVAacP+PwNNewtPqsCfWLP4mzdt37nrpvcPJ+C/64C4=,tag:ShL1LdNB8Vk0Y+7lKERUQg==,type:str]
    authelia_secondary_password_hash: ENC[AES256_GCM,data:zeNAl9fSfuMIUi0oxY90xXQEIB/pvgJb6c1Hhh4eSp3leFGL6EE+RvgCWQCakxz+TXpy3PF8awgoHDoNCnntDo7w/zyykeVFxzEur5QmJgnxpmG1Z2gPdbp5BpIkbaq/pQ==,iv:o6dHNAQ8SRsAH9tgdDLQCDsKB/Yu2IH5PolAoWxGw/Y=,tag:j5eMXJ4fMlZx+/JI+aYVsA==,type:str]
    authelia_secondary_username: ENC[AES256_GCM,data:zNC6,iv:h/Msh1JcWW1ZIK3rM6HeaK0Yyoo0AukpCSt82JoP148=,tag:Ej3h77bcGeaL9LKS8LhwMQ==,type:str]
    authelia_duo_integration_key: ENC[AES256_GCM,data:CYLT4DYGm2/BlekFVAGW4VUQoZg=,iv:iUiwXYmUU45kzVUVKqMNf44RkpHMp9TB/h5dwwsNh4o=,tag:NylHGaBW/1PWHBUyCbRPdA==,type:str]
    authelia_duo_secret_key: ENC[AES256_GCM,data:e8oQQS/Mw6l9yMR/SH+NmHQc8uT7zpXkSlVkI4w+3ofgXOA1oTHiMA==,iv:w1EnEdLk7YvHD1yXIKB5EIh+JUhP4wQ8oE5yv1H2UDk=,tag:uMyDy3i0oHUdTm/29JPkJQ==,type:str]
    authelia_duo_hostname: ENC[AES256_GCM,data:QXdTOze0OfztPSU6Q+5Qv/dWJMr2gRDRWG40cg==,iv:kFW0W4jSfHyboFgDkk7InDcOck2EUGewYdNQdDphZEg=,tag:vHaXxUbukHJaE3SW1Riv0w==,type:str]
    authelia_storage_encryption_key: ENC[AES256_GCM,data:wEE7QdCjETOu+GkTYSnicwQaCuIUwj6jbWqPKhbOW7udE6amLqpv7Vr20EmQCEkfLn2M6Qth7dLeXmEqvfEArGQBdlMlst0al4K5XFhyHeFaH2mKlaBMO+hHUVLjD+9PMxbaPYhjZGo4u9q7R4zkycDhjAkOInrk2xSYu1BlHx4=,iv:yii7geojddggCe9CyIassMNqh2x1kbPf4y6nxLP3rik=,tag:2g+CWCW6V3odStv7ZxoCFA==,type:str]
    ddns_cf_token: ENC[AES256_GCM,data:wwOs1rJRks0uP8kOOHg0UVCM3oRGlCC8KpDCAMQitwhdnK4eAgaUzA==,iv:Ji69hs3MkstSRrg534T1NhMupT2jc6VUwx6hIIYlhj0=,tag:Tow0gnMs8Ci7V2/XdcTPJA==,type:str]
    ddns_cf_zone_id: ENC[AES256_GCM,data:9NWK3t5LGQq7UekyOTIrB0AJ5M5d2UdyrJppSJ6P98Y=,iv:RsR/knppxIzaxpcp7WzcOL3jv2sEGtGeTMf7nPU4nME=,tag:iAr9KRb1VPdZovYKBsiPnQ==,type:str]
    phantombot_discord_token: ENC[AES256_GCM,data:S6AIRnnpDe1siUjKRvjqjh1PyMUredtuJEHhbqm76bHqunNq0xFU7KQ2kCKSR/rNAAuJsIbQrnooQBc=,iv:MyN9jvFoqa1DS8PfMCpGQDpevnuQRgyH5eIrYuDDnzY=,tag:8IkpamrBhnvimeKsMI4OQg==,type:str]
    phantombot_web_password: ENC[AES256_GCM,data:T3mNQAz8h8R2Gxw=,iv:WwzpUH+Fg0+aIdwIWe+404Ct4OZv2F3ChrzNscUJrjg=,tag:0+F8we1lYAeRqarZhpWwFw==,type:str]
    phantombot_web_username: ENC[AES256_GCM,data:DhA8,iv:WMXOPvBsfpyal2etckRloBc4ObiwMWGIV8G65/MHS3E=,tag:sIR17b6kzy5oUQnNK1n7rA==,type:str]
    phantombot_channel: ENC[AES256_GCM,data:AOl98n/DV9GPlIm5lW4=,iv:3DhKk0yexybhebqoMH5f+ov4IpQ6lIdKAqJ0XgcCL1E=,tag:KYCci2uMFq1DlC7BKEtdIg==,type:str]
    vaultwarden_admin_token: ENC[AES256_GCM,data:AaIdE8d+gJTZqG6Ob+R1bZS8ERYVBkmEtHX7uZBZDpC2rYIncUTdQYZPFjTJlxmm9ghRKEGpJtGLQ7hC3VruTg==,iv:eIl84qT5MMAKafTWWpmaPMZIjuMjvgDpAJX8mMJXxjQ=,tag:k4TXUq27TrVM+Zc5xIxgBA==,type:str]
    vaultwarden_yubico_client_id: ENC[AES256_GCM,data:FJ+S2ZQ=,iv:brMhZ0Fmxn0o5oeFtmxU0PcGhhIdPAtqG9YbvDCXcEM=,tag:XVgryJIwUi3kUTA501CmHg==,type:str]
    vaultwarden_yubico_secret_key: ENC[AES256_GCM,data:4xo/OaxfX8v+Y5IUxgdwJDmBQeygJvfw/J3VKQ==,iv:kHm7V5htmFGz5e1xWkJ/ZSvm+VbZpfdt2i7SWVIMgGU=,tag:cyXYZ+9/5fYieqX8h0ILeA==,type:str]
    vpn_surfshark_username: ENC[AES256_GCM,data:Jl9nIm5lD8gQkN26bBC90VhOOljchadb,iv:MvLlalLBPkd+RTLGgyuWE//C0qEhnn56Bvwz3nHZztk=,tag:2gMFDVxo+IxyZS+BIzWSlA==,type:str]
    vpn_surfshark_password: ENC[AES256_GCM,data:orkXvXXi5Klu65rdyb1X5W8ASlq/7k6S,iv:NXmdOG+NP958KnEssYGFyoKP+Y1aU8VUuKWHP8bqznQ=,tag:avS8uBPniCKEL/4KEYJ3Gw==,type:str]
    foundry_username: ENC[AES256_GCM,data:97tPec7BgLTQbPeAaA==,iv:Shk1Gjj7rhtBlQKaR1Ef/cmwXzvwZvMWfbwFDPq9FeI=,tag:J0WQe2B3ZS6gQarxUHWWgg==,type:str]
    foundry_password: ENC[AES256_GCM,data:mET13P9oiK6GnRvLHajk6IwfY7MygBu5l+/V4+JNwE4=,iv:VQ1f3M7V/O4aOATAU2EsagNiuaLluBdK7kkQqLgTJug=,tag:zSe+4hdvSmUvMEfHyx45cw==,type:str]
    foundry_admin_token: ENC[AES256_GCM,data:l1GYRIM5xLLoCqO6X8LguobAOL1pbMEXJYdWlGcTlC8=,iv:GxlxOxgWGXlA4TvUjKh4pSVXqhnUZkniNefkX50n6Us=,tag:m/eO84nQBbknbRJlbrYERg==,type:str]
    flux_discord_webhook: ENC[AES256_GCM,data:fD95GSJUwUtalow9GtzDQvOnBBe/hgAy0hawH5K+qqME96tDvb8anhGYEwnZwH9JeN2zU3iuo2M5vVHxVL+T4Dge2CrtPvvMAzmpPLMmM+KYYgqJuCV34ZUWT8H3VERF64uDfY1daWRWi4f1hnzlQWo7/jrHSUKV,iv:KT90F4dS1bTRdsc0mhoJOu0069XpoXDZxIviRe/A99c=,tag:Cr75AM02+7/5NIdi/OyySQ==,type:str]
    grafana_admin_password: ENC[AES256_GCM,data:1s/I88Pg0PwtOSHd3JOC/mrwLrjmbdA5V42OMrmEJ2w=,iv:c4hySp1rD4ipxoe7AvHWY2qDc0W7kx+09nMD87qIkEM=,tag:tNYeelHGVtEYZHJc2jdeXA==,type:str]
    alertmanager_discord_webhook: ENC[AES256_GCM,data:l11K8SwqqXk6TgKvRlzlUHU4lYMZ0HmuDH7N9eInwEKkkdmyQRC/vOkOthzVCWBcDnlz7RKdzx/aA+83Eq/Hg7sBoFR2Cwj49qb/ONCggNXEJcSGtelCK+YfGR8f4m5xYwJ4J7epwXABhnbgCPLaenJj5HBcBaYGMdrgW84E,iv:xncL/KRt5tvXjlifNLUxaynXNSKm8cElriorXP27oHM=,tag:hs8e1wnJ9MHqX9eVEF7Z2Q==,type:str]
    mqtt_ip: ENC[AES256_GCM,data:W9S4uZL1u+8TzpWRVg==,iv:2QPStwNgvaFU3ZEMmdZiZOyJpPgQMysDSMqM4fqY/GE=,tag:8Ta1zXxSiJd3CYR7746rCA==,type:str]
    camera_password: ENC[AES256_GCM,data:5KJlAIfIMxMqLg==,iv:23zVOM0vhOgDWBxZ/rOowdciHyL4EE4S/PWcQ83EM1s=,tag:NKNRkoIc0JTKvy1G2yiTxA==,type:str]
    traefik_load_balancer_ip: ENC[AES256_GCM,data:IeHySujUJiDVsQphhg==,iv:9JWfNSWxfpbtkWRngRPyrQbsoVQT4BktdcjR7KIMGEE=,tag:Aj/VnaUF0yg3/xU8JPEksw==,type:str]
    traefik_internal_load_balancer_ip: ENC[AES256_GCM,data:86ZjQBSbMaIY2by18g==,iv:9bYfkLoV2b8vgJjbZYdP9+Vkcj3ff4IsWS8te4+O2q4=,tag:x85Kepykdo/xQm6JwZCKSA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exexc7wwauqfja4j85n4hrc2rwgvvcykl9xv9y2rdhlvk5x653rqxs980a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVnAvV05jWDR0aFJlZm14
            d00vRVcrQ0VXVU5reE5FM05VMStEWEN2dnpnCmxiS1ZtQTh1aTlISVNpR2tNeElz
            TlBjaitsL0puUkxTYzlUQzh2azdId2cKLS0tIFY4UHpVT21BRXl6NXREa2oxVUdk
            cnVaWm56SXk3TFBJdUJsd09YT2NHVXMKsIonosk153P/s5480zMrq3NJnvNL0zsj
            iBFs+HKFh7LxRAqen/UWypoTwmihZz2n1h4ASzMHw23StTK8wo5gHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T00:06:28Z"
    mac: ENC[AES256_GCM,data:Js8uAolZvd6d4jyaPZKp4PYTWxsBhgmkjd4roUlgaOup5H7dGVLno/JyvimDxThZLJcj4vPq4PdJV1MGWvbEaY7FMLmiqW+bH6CgfTF4B2zd3V+qFmdCQMchZ5sIsnQrOOfBBO0iLfXAEvrmsE/BpJZ39xXaaeZlanb50kj1JoY=,iv:MsF3aldU8gowhfxHeBAaZZuU/9v+coy+UEGbIdKjf3k=,tag:IQy0BvqDyPH8edrN4+4jzw==,type:str]
    pgp:
        - created_at: "2024-12-21T00:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/UsJw4CqTVLh7JkJ8IgOGFdoRebA/DJ1GOOsep/CotW1N
            tRLlEboHV7CePf5sWvwMB58mZry1Zo/sv4UfKCnZeHMy87NidUyM3gjeD+My//WM
            2P4SoTuU4i1Ae+y1LuSgOl6l4t3Ntiz4Sv49ChaaXzHv15oHJWb5yTPITGPuedIu
            VzQFeyM0xBaMPH/WjXpFTCA1RMkKR/NXx9dIgqtcuD+sBzRv3DFdhGpk9SfllBg9
            2vljlsEBGzP94CED8Doz3rpdfLHDi3CeOvNC+FB5yZ89klAFZFEK9SEA+cGxEI8Q
            jqvDOCxmX0S6b3tGpqPLCiXgW45T+/z9dOKJ7aFIB9JcAQlPPntgeVOQEXUUqNgD
            bV4yL9ySiIo2sMlH1M1op/3OaqJF+DpAdcj5Me962R2SQcQAKeO49DTz5K/M0MlT
            l/0cJJOK8SaM12UPCLC+SRmxZhGbqnssZ41KvLg=
            =/03M
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2024-12-21T00:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0ARAAmD6eg8LNurfce0hAaRfgzMA8OkrUEbvgeCcDliBZM+ww
            u5T9d+9JPRSv8VQYA5RWKdwIsfSvyWlHQXECIL3yg9S2aDnqX8wIiYx48GXlNWyY
            gYSa9R3f99PJFh/PwAxHTfjPs+gA94nAhvpbzgN+LkcvlXe28m+6RnUXx5tfn73/
            BomzHHxYhxAIp0Od0oLyirWirzn4gtDqxK0oEjWU3MPjfU2nCcgGat+IzEk6Z6Ca
            Ir2b5nACQAELxAKrOYy96W3OeAbxkq00gMnaVLcV1/rYYwr3YnJ3JEAvD9sKB+R1
            H3cgETlcoEbqHnUnCHQ+2bJ/VEcXL9+s/QxNbUnR6xLxa5ktFdyt1y60TVtPMKZE
            qp0SWaCk3+wjBXHNxfI26u3r2RBGWYfWkieSud2rP5qzFDgc/kEIkdghhCbIsEWM
            xFnlvWQxWdwNrG73OXSlvF6TvgxEovO9GAzYQGd6iMHkxG6DJ1w4L022HqsPx55o
            v2JH6uHr4c30TkG9YcS54rUw9Xz7z588vaENHunChphNwOGbx3BWnoBxmzRxbkCM
            mbScI2nwolFYfFNhM7al8MCt84H2AIKuhR+XQy8ZcLqkv5wKNDasGp7jpH/2n0KN
            RPPbyCOSBs0XiTwwY95pqtBesElF2IFqwMDLUgtpLfA7v/IXw+Drm3EA7bv5MVnS
            XAFaYn11jfKouiqr9ORqDXLY3ZbJB0N769hINUOiMefglr2s16/VaorCL6cT8p7n
            ZzQh9IlYqLk3hYjt7nxhnNL9YCzGVDbOnFlBSR48plOWgkrlchhFoZjPibsy
            =2bBs
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2024-12-21T00:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/+In5y0hirah2rfgiCFI0RGxcdqzutNz3OlgTlz359QFL9
            4hmrRUU3U0v2AvOg/WwsX58B44MaQb2+s8lAmZl22eHoXT2DHj0Idxz0K+E9PzXX
            UoYWp1jNpQzMUEnAsqhYexyY+notj5HiJimmpfdLCGUSYr4gGunBppidCEDJ9iZV
            qzfdE/ol5QwPGqNkDGZ+anID+IuF8CHmlm9Uy3YegH3Ft+aufodGV6xt0WOKzDA6
            9nQcZKmxfWjwpPiJwips/NnIfnhRxX/wgmjgf/ViGOymJRiJPADIGM+D+YOxz3vN
            X8s40A0ITkl52vFmHFKBZblD7G1Gm/j4OgYMavWfIupDrRwuEoPZXzzfHyNcxlIT
            b7+U85CBemZaskPOcPCosUot4CxCPst38qqtf8PAqxkf5AN6ypsT9vR/TO+pMRsE
            BQ2W/+VEfCcVnSZj+ho3Vvp9trPCszA25GGIu8qQx3wtClYahmGtzKauib/Ulq25
            RTiJdhRy92PWe6e/X35M2iwxJuHac+QDSljja6+6FpazeCFoYali11OcTScUxq0l
            VFE+2caQfE42qdoyaCHxTfahIszL0kGj7YpLyNijwAGccmvcUk7dYP9Fa1g7wKvu
            SlxsHCGVxHNHEbwQym99PWA2D3czspkVCUqoTdv/wC4vl5M0dhqZnf11TFfvStPS
            XAH1mlRbQ4jqiwIsKg7WfY0EhhxURipt7YxX4zOr6J40mKK/tf1Yw7PRkx+ZfPOl
            zfTezL3nRB3C1bmzTjKUrrX/7eDxeDlRrR10OW3UoTr1b5wAHKIbO7EwHTbe
            =Wwm9
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
