apiVersion: v1
kind: Secret
data:
    docker_host_ip: ENC[AES256_GCM,data:+KKvTQkH4x3WRtxY7w==,iv:mLLjYpkpijabN9a4ehRm97kOIMtM0dIaWOSNq6exPf8=,tag:I29T0kLSXiddVu6IbzHwog==,type:str]
    domain: ENC[AES256_GCM,data:lCm78LslRyNawe56,iv:744UMhIwKADmj8zT5DL+9hK6ySy0P2DYWzOBDMRwVcw=,tag:aZqBczp2m65vnjarBYRNtw==,type:str]
    email: ENC[AES256_GCM,data:zAZs9045XjFL1tWuATh0uWRd8MtdiA==,iv:mxuDPPGTB/ww36X7V9WUoB/tk8etv+00GRzHJt9s2n8=,tag:aWKgv/IqJhkvgyy1YRVhlQ==,type:str]
    network_subnet: ENC[AES256_GCM,data:bNdYFi8Bnd62v82tT2A=,iv:TeQvRHyn67oY6fCs4KirUXJvJhGQ6gyy6Q22r37d39s=,tag:dz3KVu1PUf0YSnAWfLLRIw==,type:str]
    storage_host_ip: ENC[AES256_GCM,data:KK9WoZaGx4UjMe7l3g==,iv:lyqmsWDQexPOzcJb2GsBjpijtxIKQmTduKPNcGNwgoE=,tag:K4eCD4bgahiqSwE8fiWH9Q==,type:str]
    traefik_basic_auth_credentials_hash: ENC[AES256_GCM,data:/T7g6Qu5XADei1D0wMes4R/050HSxRij8yoUbyvDaL475qrrhatFzV87jPKtMrWi0u8faiczfUvb1235F9mhCmzG,iv:4L4xKubDrx1ju+juhkNUL5ko4I32adQshKgTYx+q+Gk=,tag:HSNG/Sp97qAcZV/rhR9FEg==,type:str]
    #ENC[AES256_GCM,data:GsLo/DIdQWDb5/inkM2syCCTJUAFlLyM24zAOROtyhk7O9PVQnJfXpyjWFYu6a8NxCqjbpSAoQ==,iv:5jXyaY8dJjglKRjakLkh0LyFoOSI0aN0V8/GCFaQiXM=,tag:FsFzMmvB/P09FaAa6TZtVg==,type:comment]
    authelia_jwt_secret: ENC[AES256_GCM,data:FR9iPJyPCmbh6irft7XaENuVNxMr3ZyzFPj8Ocp04co=,iv:MK4U1ihBk8TX6RaoLcjSeWYnJYFG2xOg8zUp1hb5Tr0=,tag:If1uaqq2qVzPomRdhG53Bw==,type:str]
    authelia_smtp_email: ENC[AES256_GCM,data:kV2y32jOghVpRs/xvVEjeSZczuPc/j7+Zoc=,iv:iR4gSDbJ0PoXAsQ5wNGXZPEjbgkuQ1exeVofayIM534=,tag:NisDi/n6bOD5UC4LrfDZBQ==,type:str]
    authelia_smtp_password: ENC[AES256_GCM,data:LMiWSWTaF1db0rZ2WicAUwZ4Z5M=,iv:HSadZaJN2K6+QzFkjwY2F18TWswhwk2OO52UaUNRfuU=,tag:cx6YZhV3QDVhMbHTLxu8ag==,type:str]
    authelia_smtp_server: ENC[AES256_GCM,data:3m8e19DagUViW3KXkA==,iv:sNlV56QaKZQTI5owpickNwSNBTnFoyDV+daE8K49qKQ=,tag:yxWktF0L3oMFRSGQVkPaOQ==,type:str]
    authelia_primary_email: ENC[AES256_GCM,data:ADAPIicxgJQFByiBc3if7diAn96pXg==,iv:KUbgKk81MiKy408Y5PZV3YzW2/W8SYO4+wMIPpAzYt8=,tag:dBmzMyr9QeZw14T74C6ZDw==,type:str]
    authelia_primary_password_hash: ENC[AES256_GCM,data:n3vEeNnEIKhd0V7iyqVNnL6MDEm6Sg9a024ve7gWVAs4d32WujIAUZhVHz7/cKUmkx9wVzVauXCelaDaRXJYDRvI9xk8yxEaoBUIrjtTmQabfcFwL/ZGE2Zd219+VClHvQ==,iv:T23t7gJQHDkc+62PjMw1lysH0YvHbFKqOnxcjs4bsTY=,tag:FeEz6ZZL61/TVs88yhOb/Q==,type:str]
    authelia_primary_username: ENC[AES256_GCM,data:w2EbVN4=,iv:5+b5xEq+Zj5yPW7m2VEFZAgJEyFqYDqAubV/Xv6pXj8=,tag:GmarMgFVRbQ+XDp+tcbQWQ==,type:str]
    authelia_secondary_email: ENC[AES256_GCM,data:UQLAV9L9YoH1nHsmqlofmg==,iv:1hIRa0eBzJODoF92COV9672g8eQCXzVEFs7o/joYN3Q=,tag:kSa1R1PUG4WlJf7/07O2Fw==,type:str]
    authelia_secondary_password_hash: ENC[AES256_GCM,data:E6SzOEJq7j4YTEZc1Iqaw+3BAstHZe40J9Jx4b8Muy3Lsg6+pqf49wvZceyLE0xvYxfOLtFvfTu3w3QG7793IjXtSrD06f+bKNLwmIBjy2a0mWjseU/JcqmGeKD8q6BrQA==,iv:53CjjIftjRc17l5x41lggBYJw+9FL3L6jjnpFpyVclI=,tag:EUTaZZ1b4uTok1kec43xKA==,type:str]
    authelia_secondary_username: ENC[AES256_GCM,data:l7d+,iv:lka5xGZxoK67ip5irYsYCAnkZxbhu0ki8LM1Dc5p8K4=,tag:id7Eve567Hp7v18RdDVPhA==,type:str]
    authelia_duo_integration_key: ENC[AES256_GCM,data:2u47vtwcJxiX1R6NaFpN8eHlSaA=,iv:GkMGrj4w3pDvyH0FWMec63mWGI9ubV2gFTc07kcTsYg=,tag:03iEnmMkQD+OawRudUoVVA==,type:str]
    authelia_duo_secret_key: ENC[AES256_GCM,data:dvLokdBZuPfSGKJbojOQyH4J+VXIsOazwPzvckbhjtoZzrgsEfvUMw==,iv:iJ+qRumUxtedL79qn0yM9Q8MHTIGd4vi6R2SukZL2V8=,tag:VJGw+YmaYwJwhYwVe12MsA==,type:str]
    authelia_duo_hostname: ENC[AES256_GCM,data:yx/bb9imovvf3K44CGJUNo59i5c9OyU3c6yIfA==,iv:oFKzU9ysdJJKCvNRtumksuKzqSbv/0fB5tYbMfwOZPs=,tag:NxWg2DzazpRA8FJPn/rQiA==,type:str]
    authelia_storage_encryption_key: ENC[AES256_GCM,data:h+41jsObHtE/Xqs2aIz3j9e44ivBH9eaoOco1ui7PiqN7e2xxxGqAOn08/tMmHRPUgx604JYrT3e9Uzzd9J+3H2YWdf2NdExrnnRDoKb4UA0rLs21IffZu5jqIckgMZStJkGKNCRc9j3XCzYm5OZUMPtJXB/SmErqmpoISM+ylk=,iv:ydt6XFnJLAB/vtZgTJQ0ccGcA89h/slZiSgFIwe4KfI=,tag:s31MPwi5ypxDTy0/L9ioKg==,type:str]
    ddns_cf_token: ENC[AES256_GCM,data:eVrunbJefP3luHiziyCLsD0Mvsphjnuo0LCdW+iMYAomz9wZurgtcg==,iv:XQmW5ViFZ5dY6JVBdCgJoKveihCOTe311/IpMDZ4qeY=,tag:7L8J0gq0fVPWR6rnpPvOYA==,type:str]
    ddns_cf_zone_id: ENC[AES256_GCM,data:ndf7LvAbja0WiGe2uIqZdesCUl1bYtSUA0HUZxCGRTc=,iv:IF3j8Cw8rL9OpjTsxURGT0/9Ct4Jea5t5QiP81aA1Hw=,tag:qPLJK+ZiDwNRQZ8BFH22VQ==,type:str]
    phantombot_discord_token: ENC[AES256_GCM,data:OI9/peRsYpK5g/UXNToHCuifPpH9KQuyeOWwOHKGg2DhzfLgp9NZ6EH7BhoYoyBh3ArD5e+43D9rxH4=,iv:UdW7FkdZjBMlfhAnQjf05dwsAs4E5m/nU8ZFATzPODM=,tag:BMTSWvczEWBxJJIFbT2VfA==,type:str]
    phantombot_web_password: ENC[AES256_GCM,data:vKcmUMwDGmrhW+M=,iv:kVAaBayquvlGPce0cdNwpz6x1vGS6YwE9v3XKT5VT60=,tag:oGe80wPo2bySPyVX22bDWA==,type:str]
    phantombot_web_username: ENC[AES256_GCM,data:FNqp,iv:4304Er+EwragCh+GGUdfXDsaDF7GzwyV6uB8F4VNlHI=,tag:yGaKAv69cyJqsXueAQRf9w==,type:str]
    phantombot_channel: ENC[AES256_GCM,data:1Ff3RFeBGHFI/0CIFjE=,iv:Q4gcqJL5zcDPtZhW3+yk4EUZcyEsqYkPpxwkHPP3NVE=,tag:rGjKtdjV4OQjDkqvjSsdiA==,type:str]
    vaultwarden_admin_token: ENC[AES256_GCM,data:tx0LdvVm/r9NIrIX2sLSCibcAq6ONCusE79RUUswfL+RXZgOPNAIKVhg+O2V6u5Pa1GKQR/k+UN6jZ42V8LC1w==,iv:3ZWZ1tr0+0Wha9Xc6EvDVzz0kBQpyMgjrIQjOS2iZQk=,tag:2mdIXFdyoOIjLtVM8M5JPA==,type:str]
    vaultwarden_yubico_client_id: ENC[AES256_GCM,data:1Ocs5pA=,iv:zP+0BxySVzBoUqV/tvYTiGD0fdfCA1l0jZ1pjVHu7Gs=,tag:eAgrFsw8IbvTKAFQVmPHpg==,type:str]
    vaultwarden_yubico_secret_key: ENC[AES256_GCM,data:MKxcRTHigRMhy4c6zUA7hXbEkBcdr02a5EuYWw==,iv:Vc6+y3VRMZ2gFOs2yCDQhgWRRh5ipA05CxMAgD4nGY0=,tag://nKx20weUUBpClnxFEGIQ==,type:str]
    vpn_surfshark_username: ENC[AES256_GCM,data:6nqQAWYeLUOFRfKZCr9fLT2VklJyjnRp,iv:OzXIuDIp5MBiv2Og/Vu6HpwVetfnzBQh6J7V8tZ2uAQ=,tag:O9/bxICnklgPz1I64rjX1w==,type:str]
    vpn_surfshark_password: ENC[AES256_GCM,data:vkObQRypLD/nBpYMHYntJki6pb0EfMJ6,iv:uDB/IPJUHrswbDng9TZuH/9amfELhxFIiB1FETUxDVc=,tag:PwuAKwCRDOKa0pT4mHOoFA==,type:str]
    foundry_username: ENC[AES256_GCM,data:PAi54XNb9DshJSIekA==,iv:bDAdfK6Vs7Q8h7VxUVY7D/VQSO4DxK59d1mTi7Hz7Fo=,tag:7NhOf7KLv2bYXm1ctXDSKQ==,type:str]
    foundry_password: ENC[AES256_GCM,data:jcz6W6QGZYch4QljT2hbhxuCgEZz2MwoFrq2f5LdEhs=,iv:rChrdEaFZjo9AiOYPPmT7rieb+xPLakr2KmBKmCjuS0=,tag:RHYLrtu7awlo433IlHQbKw==,type:str]
    foundry_admin_token: ENC[AES256_GCM,data:9NxqBKL2IDKj8n6VpnbJRQ26PMyGOHFhpX5q7mvWTQY=,iv:nseFe+sSMMpXU0G/vwOzIJQZ03pusumwvNMirM4KoT0=,tag:bePYeMGDRBlHQm5Ht3oHxg==,type:str]
    flux_discord_webhook: ENC[AES256_GCM,data:XVBb35HwSpcWg0NN8m80HUB4C4tTnKhBkGt6FIm4KM7Ga1ZXNUgtWHW9AEn73MYUFzNcmYND/lYyf886vfEhLQ57psa301Mq+0LdknEyV0TFU3RvMl1447sHINjktzrwROf3v02NOVv40g19sGoW0tfkYSNSh7H0,iv:g9WrrrPEXcXElKfzu4Z+4TrTZnJGmrMB393P6O+wK4s=,tag:A99uFNo5nRR/vbSx2pRoUg==,type:str]
    grafana_admin_password: ENC[AES256_GCM,data:QNP3S9ghyXgiE2vEQgk5k1s9pQZYjYo8e949TV1AU0A=,iv:HIVs5tAcGMZf7+TVu142bAhsWvWoijfXV6u7myPGyZ0=,tag:iM9J69fLp46+Hl+2aF3dLA==,type:str]
    alertmanager_discord_webhook: ENC[AES256_GCM,data:BWjB1fQ1+AU2hJZFw/kGCUmN7lMK1lIpxA4nJEODGhDuMIiBbOIL65kvabg11dnawzdyOsoQ2Yjz1pcQFqgb9obI961FwjulYnRYi/dxb+lBwvKlNBmpigqom4euFnV+ZAt010JJsU7OuLUMC30vMu5q//TRvDiHXOX5vJm1,iv:48bZHi6NE0g22yUOa+S7HaM/vtgvxr4KTCC7QpM5bhc=,tag:drH4AUbbRaXLOQ41o9wgrQ==,type:str]
    mqtt_ip: ENC[AES256_GCM,data:q1AjPiKG2hVQ5eEMrw==,iv:cg25O8yRqX9SEwfUfbJVOUOomoi0DEDQNP7haDdxrDY=,tag:dBgbzUIBBnYJwT/VqswX4A==,type:str]
    camera_password: ENC[AES256_GCM,data:2zwymdyMzf/t8A==,iv:JCmo8yj4GfuGlX578htCGMBE0OCReDtGOT/zrKA7Vl4=,tag:QSKBq/knQqM4AW9FQXHhSw==,type:str]
    traefik_load_balancer_ip: ENC[AES256_GCM,data:Jd7dSpRNy8SBTqPNoA==,iv:aN/Jr4byJfEowGvCf6NFYEAM8hC6C9vpGRA3++Y87mY=,tag:nLehQfTvlpBT3780rX+HKw==,type:str]
    traefik_internal_load_balancer_ip: ENC[AES256_GCM,data:33i+ItF6WVMfQis1xg==,iv:xt1EBMqmQUBR918EW2jGluzx877m9J5NCR8lQsyziNU=,tag:wGeCEo2K+MuIrAYjCMcv1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exexc7wwauqfja4j85n4hrc2rwgvvcykl9xv9y2rdhlvk5x653rqxs980a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVnAvV05jWDR0aFJlZm14
            d00vRVcrQ0VXVU5reE5FM05VMStEWEN2dnpnCmxiS1ZtQTh1aTlISVNpR2tNeElz
            TlBjaitsL0puUkxTYzlUQzh2azdId2cKLS0tIFY4UHpVT21BRXl6NXREa2oxVUdk
            cnVaWm56SXk3TFBJdUJsd09YT2NHVXMKsIonosk153P/s5480zMrq3NJnvNL0zsj
            iBFs+HKFh7LxRAqen/UWypoTwmihZz2n1h4ASzMHw23StTK8wo5gHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T00:35:32Z"
    mac: ENC[AES256_GCM,data:REd6AsAjWO4s+iVhjZj9ADBj718FklNeUDkfx8z/QOwDp5e7y6KkBRKmpWuNRaQspC4wrkfVnLKELMfc4MIap5mVMkM6hXEVLVvFzsEOU4fBU7l7JBKs6g/QCjTk0bwdinFZ+Cz9Jd74J9y+E64bwpp7PnCaLbYrw4rtp8umuaQ=,iv:botmD9xmlKhqlUVdPhQUGoYcPaejoPCGSE2JyoIy4eI=,tag:THLKmRBjIX7JQ34+EdkBxQ==,type:str]
    pgp:
        - created_at: "2024-12-21T00:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/UsJw4CqTVLh7JkJ8IgOGFdoRebA/DJ1GOOsep/CotW1N
            tRLlEboHV7CePf5sWvwMB58mZry1Zo/sv4UfKCnZeHMy87NidUyM3gjeD+My//WM
            2P4SoTuU4i1Ae+y1LuSgOl6l4t3Ntiz4Sv49ChaaXzHv15oHJWb5yTPITGPuedIu
            VzQFeyM0xBaMPH/WjXpFTCA1RMkKR/NXx9dIgqtcuD+sBzRv3DFdhGpk9SfllBg9
            2vljlsEBGzP94CED8Doz3rpdfLHDi3CeOvNC+FB5yZ89klAFZFEK9SEA+cGxEI8Q
            jqvDOCxmX0S6b3tGpqPLCiXgW45T+/z9dOKJ7aFIB9JcAQlPPntgeVOQEXUUqNgD
            bV4yL9ySiIo2sMlH1M1op/3OaqJF+DpAdcj5Me962R2SQcQAKeO49DTz5K/M0MlT
            l/0cJJOK8SaM12UPCLC+SRmxZhGbqnssZ41KvLg=
            =/03M
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2024-12-21T00:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0ARAAmD6eg8LNurfce0hAaRfgzMA8OkrUEbvgeCcDliBZM+ww
            u5T9d+9JPRSv8VQYA5RWKdwIsfSvyWlHQXECIL3yg9S2aDnqX8wIiYx48GXlNWyY
            gYSa9R3f99PJFh/PwAxHTfjPs+gA94nAhvpbzgN+LkcvlXe28m+6RnUXx5tfn73/
            BomzHHxYhxAIp0Od0oLyirWirzn4gtDqxK0oEjWU3MPjfU2nCcgGat+IzEk6Z6Ca
            Ir2b5nACQAELxAKrOYy96W3OeAbxkq00gMnaVLcV1/rYYwr3YnJ3JEAvD9sKB+R1
            H3cgETlcoEbqHnUnCHQ+2bJ/VEcXL9+s/QxNbUnR6xLxa5ktFdyt1y60TVtPMKZE
            qp0SWaCk3+wjBXHNxfI26u3r2RBGWYfWkieSud2rP5qzFDgc/kEIkdghhCbIsEWM
            xFnlvWQxWdwNrG73OXSlvF6TvgxEovO9GAzYQGd6iMHkxG6DJ1w4L022HqsPx55o
            v2JH6uHr4c30TkG9YcS54rUw9Xz7z588vaENHunChphNwOGbx3BWnoBxmzRxbkCM
            mbScI2nwolFYfFNhM7al8MCt84H2AIKuhR+XQy8ZcLqkv5wKNDasGp7jpH/2n0KN
            RPPbyCOSBs0XiTwwY95pqtBesElF2IFqwMDLUgtpLfA7v/IXw+Drm3EA7bv5MVnS
            XAFaYn11jfKouiqr9ORqDXLY3ZbJB0N769hINUOiMefglr2s16/VaorCL6cT8p7n
            ZzQh9IlYqLk3hYjt7nxhnNL9YCzGVDbOnFlBSR48plOWgkrlchhFoZjPibsy
            =2bBs
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2024-12-21T00:06:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/+In5y0hirah2rfgiCFI0RGxcdqzutNz3OlgTlz359QFL9
            4hmrRUU3U0v2AvOg/WwsX58B44MaQb2+s8lAmZl22eHoXT2DHj0Idxz0K+E9PzXX
            UoYWp1jNpQzMUEnAsqhYexyY+notj5HiJimmpfdLCGUSYr4gGunBppidCEDJ9iZV
            qzfdE/ol5QwPGqNkDGZ+anID+IuF8CHmlm9Uy3YegH3Ft+aufodGV6xt0WOKzDA6
            9nQcZKmxfWjwpPiJwips/NnIfnhRxX/wgmjgf/ViGOymJRiJPADIGM+D+YOxz3vN
            X8s40A0ITkl52vFmHFKBZblD7G1Gm/j4OgYMavWfIupDrRwuEoPZXzzfHyNcxlIT
            b7+U85CBemZaskPOcPCosUot4CxCPst38qqtf8PAqxkf5AN6ypsT9vR/TO+pMRsE
            BQ2W/+VEfCcVnSZj+ho3Vvp9trPCszA25GGIu8qQx3wtClYahmGtzKauib/Ulq25
            RTiJdhRy92PWe6e/X35M2iwxJuHac+QDSljja6+6FpazeCFoYali11OcTScUxq0l
            VFE+2caQfE42qdoyaCHxTfahIszL0kGj7YpLyNijwAGccmvcUk7dYP9Fa1g7wKvu
            SlxsHCGVxHNHEbwQym99PWA2D3czspkVCUqoTdv/wC4vl5M0dhqZnf11TFfvStPS
            XAH1mlRbQ4jqiwIsKg7WfY0EhhxURipt7YxX4zOr6J40mKK/tf1Yw7PRkx+ZfPOl
            zfTezL3nRB3C1bmzTjKUrrX/7eDxeDlRrR10OW3UoTr1b5wAHKIbO7EwHTbe
            =Wwm9
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
