---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - blog
  - crowdsec-web-ui
  - flux-notifications
  - traefik
  - kubewall
  - flux-operator
  - gatus
  - lldap
  - pocket-id
  - postgres
  - tinyauth
