version: "3"
services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    restart: always
    volumes:
      - /homelab/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - /homelab/dnsmasq/dnsmasq_hosts:/etc/dnsmasq_hosts
    network_mode: "host"
    environment:
      - "HTTP_USER=foo"
      - "HTTP_PASS=bar"
    cap_add:
      - NET_ADMIN
