version: "3.5"
services:
  dnsmasq:
    image: andyshinn/dnsmasq
    restart: unless-stopped
    volumes:
      - /homelab/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    network_mode: "host"
    cap_add:
      - NET_ADMIN

  #cloudflare-ddns:
  #  image: oznu/cloudflare-ddns
  #  restart: unless-stopped
  #  env_file: /homelab/cloudflare-ddns/cf.env

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns
    restart: unless-stopped
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /homelab/cloudflare-ddns/config.json:/config.json
