version: "3.5"
services:
  dnsmasq:
    image: andyshinn/dnsmasq
    restart: unless-stopped
    volumes:
      - /homelab/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    network_mode: "host"

  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    restart: unless-stopped
    env_file: /homelab/cloudflare-ddns/cf.env
