---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: mosquitto
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    hostNetwork: true
    env:
      TZ: America/Toronto
