---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.22
            env:
              TZ: America/Toronto

    service:
      main:
        controller: main
        type: LoadBalancer
        loadBalancerIP: ${mqtt_ip}
        ports:
          mqtt:
            enabled: true
            primary: true
            port: 1883

    persistence:
      config-file:
        type: configMap
        name: mosquitto-config
        advancedMounts:
          main:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
