---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.18
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            primary: true
            port: 1883
    persistence:
      config-file:
        type: configMap
        name: mosquitto-config
        advancedMounts:
          main:
            main:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
    env:
      TZ: America/Toronto
