---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: games
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest

    hostNetwork: true
    service:
      main:
        ports:
          http:
            port: 25565
            protocol: TCP

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - docker01

    persistence:
      data:
        enabled: true
        existingClaim: minecraft-config
    podSecurityContext:
      fsGroup: 568
    env:
      TYPE: 'FORGE'
      VERSION: '1.18.1'
      EULA: 'TRUE'
