version: "3.5"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    networks:
      - webnet
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Toronto
    volumes:
      - /storage/nextcloud/config:/config
      - /storage/nextcloud/data:/data
    deploy:
      placement:
        constraints: [node.hostname == appletini]
      labels:
        - traefik.http.routers.nextcloud.rule=Host(`nextcloud.joshwolfe.ca`)
        - traefik.http.routers.nextcloud.tls=true
        - traefik.http.services.nextcloud-service.loadbalancer.server.port=80

networks:
  webnet:
    external: true
