---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-web-ui-data
  namespace: admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
