---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qui-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
