---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qui
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/autobrr/qui
              tag: v1.5.0
            env:
              QUI__OIDC_ENABLED: true
              QUI__OIDC_ISSUER: https://login.${domain}
              QUI__OIDC_CLIENT_ID: qui
              QUI__OIDC_CLIENT_SECRET: ${authelia_qui_client_secret}
              QUI__OIDC_REDIRECT_URL: https://qui.${domain}/api/auth/oidc/callback
              QUI__OIDC_DISABLE_BUILT_IN_LOGIN: true

    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "qui.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 7476

    persistence:
      config:
        enabled: true
        existingClaim: qui-config
