---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: utils
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 3.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.22.2
    ingress:
     main:
       enabled: true
       hosts:
         - host: "bw.${domain}"
           paths:
             - path: /
               pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /homelab/vaultwarden
        mountPath: /config
    env:
      TZ: America/Toronto
      YUBICO_CLIENT_ID: "${vaultwarden_yubico_client_id}"
      YUBICO_SECRET_KEY: "${vaultwarden_yubico_secret_key}"
      ADMIN_TOKEN: "${vaultwarden_admin_token}"
