---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: utils
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
releases:
- name: vaultwarden
  namespace: passwordmanager
  chart: k8s-at-home/vaultwarden
  values:
    ingress:
     main:
       enabled: true
       hosts:
         - host: "bw.${domain}"
           paths:
             - path: /
               pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /homelab/vaultwarden
        mountPath: /config
    env:
      TZ: America/Toronto
      YUBICO_CLIENT_ID: "{{ .Values.vaultwarden.yubico_client_id }}"
      YUBICO_SECRET_KEY: "{{ .Values.vaultwarden.yubico_secret_key }}"
      ADMIN_TOKEN: "{{ .Values.vaultwarden.admin_token }}"
