apiVersion: v2
appVersion: 1.0.0
description: phantombot helm package
name: phantombot
version: 2.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- phantombot
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/${CHARTNAME}
icon: https://${CHARTNAME}.org/icon
sources:
- https://github.com/${CHARTNAME}/${CHARTNAME}-docker
maintainers:
- name: ${CHARTNAME}
  email: ${CHARTNAME}@${CHARTNAME}.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.0.1
