apiVersion: v2
appVersion: 1.0.0
description: phantombot helm package
name: phantombot
version: 2.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- phantombot
home: https://github.com/Mulan-Szechuan-Sauce/house20/tree/master/
home: https://github.com/Mulan-Szechuan-Sauce/house20-admin/tree/master/kubernetes/helmfiles/twitch/phantombot
sources:
- https://hub.docker.com/r/gmt2001/phantombot-stable
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.0.1
