version: "3.5"
services:
  bot:
    image: ghcr.io/mulan-szechuan-sauce/marvin:latest
    env_file:
      - ~/.marvin.env
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple
