---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
spec:
  project: default
  source:
    repoURL: https://github.com/WolfeCub/home-ops
    targetRevision: argo
    path: ./argo/testing/
    plugin:
      env:
        - name: SOPS_SECRET_FILE
          value: ../bootstrap/secret.sops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: blah
