---
clusterName: talos-homelab
endpoint: https://192.168.0.210:6443
patches:
  - |-
    machine:
      sysctls:
        net.ipv6.conf.all.disable_ipv6: 1
        net.ipv6.conf.default.disable_ipv6: 1
        net.ipv6.conf.lo.disable_ipv6: 1
      kubelet:
        defaultRuntimeSeccompProfileEnabled: false
nodes:
  - hostname: master01
    controlPlane: true
    ipAddress: 192.168.0.210
    installDiskSelector:
      wwid: naa.5001b444a6774a7f
    schematic:
      customization:
        extraKernelArgs:
          - idle=nomwait
          - processor.max_cstate=1
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode

  - hostname: worker01
    ipAddress: 192.168.0.211
    installDiskSelector:
      wwid: naa.5000c500e4102f15

  - hostname: worker02
    ipAddress: 192.168.0.212
    installDiskSelector:
      wwid: naa.5000c500e412aca4

  - hostname: worker03
    ipAddress: 192.168.0.213
    installDiskSelector:
      wwid: naa.5000c500e41281be


worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/gasket-driver
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
  patches:
    - |-
      machine:
        # longhorn v2 data engine
        sysctls:
          vm.nr_hugepages: "1024"
        kernel:
          modules:
            - name: nvme_tcp
            - name: vfio_pci

        kubelet:
          extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw
