---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: utils
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Plex
                    url: https://plex.${domain}
                    icon: /assets/plex-logo.png
                  - title: Vaultwarden
                    url: https://bw.${domain}
                    icon: /assets/vaultwarden-logo.png


          - size: full
            widgets:
              - type: hacker-news

              - type: videos
                channels:
                  - UCgtOMaHBiYvsRYZ77utf8FQ # Erik Karlsson Bouldering


              - type: group
                widgets:
                - type: reddit
                  subreddit: selfhosted
                - type: reddit
                  subreddit: neovim
                - type: reddit
                  subreddit: rust

          - size: small
            widgets:
              - type: weather
                location: Mississauga, Canada

              - type: markets
                markets:
                  - symbol: SPY
                    name: S&P 500
                  - symbol: DBX
                    name: Dropbox
                  - symbol: GOOG
                    name: Google
