---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: haugene/transmission-openvpn
              tag: dev
            securityContext:
              fsGroup: 568
              capabilities:
                add:
                  - NET_ADMIN
            env:
              TZ: America/Toronto
              OPENVPN_USERNAME: "${vpn_proton_username}"
              OPENVPN_PASSWORD: "${vpn_proton_password}"
              OPENVPN_PROVIDER: CUSTOM
              OPENVPN_CONFIG: nl.protonvpn.udp
              LOCAL_NETWORK: "10.42.0.0/16,10.43.0.0/16,192.168.0.0/24"
              PUID: 568
              PGID: 568
              TRANSMISSION_DOWNLOAD_DIR: /downloads
              TRANSMISSION_INCOMPLETE_DIR_ENABLED: false

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "transmission.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    service:
      main:
        controller: main
        ports:
          http:
            port: 9091

    persistence:
      config:
        enabled: true
        existingClaim: transmission-config
        globalMounts:
          - path: /config
            readOnly: false
      vpn-config:
        enabled: true
        existingClaim: transmission-ovpn-config
        globalMounts:
          - path: /etc/openvpn/custom/
            readOnly: false
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/Downloads
        globalMounts:
          - path: /downloads
            readOnly: false
