---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haugene/transmission-openvpn
      tag: "4.0"
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "transmission.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 9091
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /homelab/transmission
        mountPath: /data
    env:
      OPENVPN_PROVIDER: SURFSHARK
      OPENVPN_USERNAME: "${vpn_surfshark_username}"
      OPENVPN_PASSWORD: "${vpn_surfshark_password}"
      OPENVPN_CONFIG: nl-ams_udp
      LOCAL_NETWORK: "10.43.0.0/16"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
