---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haugene/transmission-openvpn
      tag: dev
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "transmission.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 9091
    persistence:
      config:
        enabled: true
        existingClaim: transmission-config
        mountPath: /config
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/Downloads
        mountPath: /downloads
      ovpn-config:
        enabled: true
        type: configMap
        name: ovpn-config
        mountPath: /etc/openvpn/custom/nl.protonvpn.udp.ovpn
        subPath: nl.protonvpn.udp.ovpn
    podSecurityContext:
      fsGroup: 568
    env:
      OPENVPN_USERNAME: "${vpn_surfshark_username}"
      OPENVPN_PASSWORD: "${vpn_surfshark_password}"
      OPENVPN_PROVIDER: SURFSHARK
      OPENVPN_CONFIG: lu-ste.prod.surfshark.com_udp
      LOCAL_NETWORK: "10.42.0.0/16,10.43.0.0/16,192.168.0.0/24"
      PUID: 568
      PGID: 568
      TRANSMISSION_DOWNLOAD_DIR: /downloads
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: false
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
