---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haugene/transmission-openvpn
      tag: dev
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "transmission.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 9091
    persistence:
      config:
        enabled: true
        existingClaim: transmission-config
        mountPath: /data/transmission-home
      downloads-complete:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/k8s-shared/torrents/completed
        mountPath: /data/completed
      downloads-incomplete:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/k8s-shared/torrents/incomplete
        mountPath: /data/incomplete
    podSecurityContext:
      fsGroup: 568
    env:
      OPENVPN_PROVIDER: SURFSHARK
      OPENVPN_USERNAME: "${vpn_surfshark_username}"
      OPENVPN_PASSWORD: "${vpn_surfshark_password}"
      OPENVPN_CONFIG: lu-ste.prod.surfshark.com_udp
      LOCAL_NETWORK: "10.42.0.0/16,10.43.0.0/16,192.168.0.0/24"
      PUID: 568
      PGID: 568
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
