---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: admin
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
