---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: admin
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
