---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: admin
data:
  dynamic.yml: |
    http:
      middlewares:
        spoolman-basic:
          basicAuth:
            users: ["${traefik_spoolman_basic_auth}"]

      routers:
        api:
          rule: "Host(`traefik.${domain}`)"
          entrypoints: ["websecure"]
          service: "api@internal"
          middlewares:
            - "admin-forwardauth-authelia@kubernetescrd"
