http:
  middlewares:
    basic:
      basicAuth:
        users: ["{{ .Values.traefik.basic_auth_credentials_hash }}"]

    localOnly:
      ipWhiteList:
        sourceRange:
          - "{{ .Values.shared.network_subnet }}"
          - 10.42.0.1/24

  routers:
    api:
      rule: "Host(`traefik.{{ .Values.shared.domain }}`)"
      entrypoints: ["websecure"]
      service: "api@internal"
      middlewares:
        - "localOnly@file"
        - "admin-forwardauth-authelia@kubernetescrd"

    hass:
      rule: "Host(`hass.{{ .Values.shared.domain }}`)"
      entrypoints: ["websecure"]
      service: "hass-service@file"

    transmission:
      rule: "Host(`transmission.{{ .Values.shared.domain }}`)"
      entrypoints: ["websecure"]
      service: "transmission-service@file"
      middlewares: 
        - "localOnly@file"
        - "admin-forwardauth-authelia@kubernetescrd"

  services:
    hass-service:
      loadBalancer:
        servers:
          - url: "http://{{ .Values.shared.docker_host_ip }}:8123"

    transmission-service:
      loadBalancer:
        servers:
          - url: "http://vpn:9091"
