defaultEntryPoints: ["http", "https"]

entryPoints:
  web:
    address: ":80"

    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: leCertResolver
        domains:
          - main: "{{ shared.domain }}"
            sans: 
              - "*.{{ shared.domain }}"

providers:
  docker:
    swarmMode: true
    watch: true
    network: webnet

  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

api:
  dashboard: true

certificatesResolvers:
  leCertResolver:
    acme:
      email: {{ shared.email }}
      storage: "/etc/traefik/acme.json"
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
