defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.web]
  address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
  address = ":443"

[api]

[providers]
  [providers.docker]
    swarmMode = true
    watch = true
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
    watch = true

