---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-all
  namespace: longhorn-system
spec:
  name: backup-all
  task: backup
  cron: "0 9 * * *"
  groups:
    - daily
  retain: 7
  concurrency: 2
  parameters:
    # full backup when executionCount % interval == 0, so this is a weekly full
    full-backup-interval: "7"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: cleanup-snapshots
  namespace: longhorn-system
spec:
  name: cleanup-snapshots
  task: snapshot-cleanup
  cron: "0 13 * * *"
  groups:
    - default
    - daily
  retain: 0
  concurrency: 3
