apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mIZRcpVqCK/XSU6PlskaRq4cGUA=,iv:VdrO2zjrvo6JNQ+MsUOOPjcvP57hvHA5uh0JUA0420M=,tag:Kme13BLcUFANA2Eu2HKLsw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HjSN0F5iW1sKyd3b7+K7f7bcveV2uhUc9YEzWcm/Mgl1cZpMUWUFBg==,iv:rlRTV6dDyALX1Frp991yzdCBKTFYQJgvz+HHf8ZI6us=,tag:pyLiucDNK8hOuznAp8eAlg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:1sF63I+LRY1hR0e8mq173jiXoy2zq50uDQ==,iv:qrvmz9e9avJ9db4lh2OYRuy1wud5GxwjjFBC6jkPluI=,tag:OY29MxHevbuHcZYWJijIQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-19T22:38:28Z"
    mac: ENC[AES256_GCM,data:PTiU0tqfSXphzphYWSy4hSwCZ6+r/BIeTEHdna+owmpBu2iBvmGGCAVX8McN0/uDUH2ckHiBu4blPZT8xmR4m5JLMI463l0sIatfkwPiRWHRo3lbLPZqf1Kvc3W7+abd1r0zUGqSCXLMdOvF05Tqcu1XQTso2UA2Ep4A0g/nC0I=,iv:qv5PFGZklWKkooBb43o7nfgeCO82kVbI6ke+IWYYFEE=,tag:DXpaRbawflb6aGWkEs3p1A==,type:str]
    pgp:
        - created_at: "2023-10-19T22:24:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf+OBBieRq8njpCqMTznw7nRiXg+Lc5zlSgUeffWWCKc1hF
            aGQxhjHUyWq6UqvM94gDufI+LqUgkC/G7ocLjtqBBA1qSGvxpa1Ltrb4S6Gzr75M
            eMLyhqonwQ0CHu5LJ05V7o1QbqKowZO7oV1Q5dG71fXzdwg0mct/xDcFe8W8ZIc3
            QGN08cisWjgVNIIiV84AgiNoIqVtGkOGyFcWKYzYhl7Il8BESsOEP4uM2z8/1mIs
            LYOd3JU7iYHjhWzvu8eTYLocq+4vPch+2S2zFued88gdxxKcbJBtjecA6aEeePWC
            gEbbjECus7r4TPiMuKTGKmMkXLDtu9JSZGYa39nO8dJeAcWUdijoqegcG92NfggN
            qfZn74N7j4RgDn982pWHRyVrFWlVRfp6OBAdzKdVudMKi65jWHOOqSOjgnfTqfdy
            CdnXC96O0CRPsE9dFt9vPIurkyrqtM70Pybcf1x+Tw==
            =lCYU
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2023-10-19T22:24:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0ARAAimXI5Og6aNSDmfWCLpv/38iugJhw4OxA3GMob7f9jwNd
            smBk8+fhWQha3es+1gOwI1lp694dhluBK4tgI8jHll+9UvgRrwYvHI9Gvg1I4cmi
            IxPCQhoS6msYWfpS2JN2IvHTsaV1ZwJ8WoUJJGX03rE5uYy55Grwlj9sE3BKPc5e
            Kmw/VWPeY8jvQRuCmAm4FIuCu41Y2OZB7LnErZcJDuYwWGlQvSw7izoxnESMg5su
            EUTIs47JVyF0nXr6uHV4Vfimn6ohe1phNCE1aongtfW34PBmKw/QaIYlsTSyPoUO
            3uv7zxSZx/lS9ojaLA+rhmsphTkJHaXHaxeWxwGWS49AgI/Rt+QBRH34X2WSqxtN
            UsOMpRW3M96u4VruhBU9rkJsgStgSgFKRmGQEPieEUXjbnmQ1NuTrgVgnoW4qs7j
            S1NwbPHTcZSCeYU2czjUwvSwOSvEXszpchFc2brOAIUaFoZnncDeMoUT5EPe/tZ0
            s980G2nzXFsr6dR9Nr5VkqZoM+GtASfRlm2ud+ZdUknxV0ScmKoTzrZSYXEb40Id
            kti4NVsbGaSZCKM3kdzsOeqdtgBMpZ2gHd+czhXZbpZQMbwB+Qo802vcghRmr3Va
            NIVPzNpzb2b8zHo5Ub6FgY4FTRpP5B7sebH/aIsmQk+GM8F04MYHUw0jnJRhzSDS
            XgGGMLD+RFt+y3Z012mi5rs7glkD6VCFsXtZzdqOdJeVwyD4aTqfMPOzty/pXDI1
            G+KcRIs1rVjkaw25fZqPJgZf57XjRZtpwLibgDKgqXUT5JmuKjnz/Fs1GU0rplc=
            =1AfY
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2023-10-19T22:24:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/+MAjEdYV+JkFZ6WjNEnm7GPVQBIiMynmWXguHmSMZ6uzZ
            IdFdQE1XKqCfRSeB6FGVJXwdNp5agMyaSoyKIOcG7MNMdfZIyMb4JvmLnduz4tyH
            8xgilp7lNOodRTMSyQJ8KnUOlDoVwFFwZJ4g0MJAuvRUamDtnWaxdI9bCAU+luqq
            NEF4/JKT+r1v+9Fhyd5Mn/0+frWJBbHc1/eYN/6l7HHLY5iCdEh+zP15hcLCz6zp
            vO747q9zCOaNmnNngwGoiUXE70aBsavS4sXsHg8/18/+y23iuPt4QtAAxnAZZvmm
            bnW9UAPNCKPmBwnpMps0WN6vgVDnB2bhgRGmu1GM7AylpY4bVgjKHbd6wty3JihW
            Urty70eqSB1xoS6YqmzlbvkUGBa7A8foEwAwyYR+MpNyOv3SFzJ4/xJuTj07PPM7
            Uai3lDYxtvzgl8CVLVCVR0ymEp/g3v81txmb6HvvmGSeLFwnvRARWGwHVZKRMOFu
            7rWNCoLajxDTCvAdnTm5tCDZJ7kt3GA5BptjQZY/YvRuK6I8UUwb6nK3TYrg9ToG
            fAxREPb/rAl1TXLiHctU5abBwKSlP0i3TRJauq5/OOj44EYuuj/WLCIOf2QWwrxg
            nPapPMsjJ1+IFjP+8rYwxoUlF+IWwpCWAgfK7UbvYQjQO+mHhPMbOTlqmjN/jEfS
            XgEhZ+o1F6Up9I0o7yrIu9t4jB7X4GQzpxy5UQqj6XYGpOBF57X88Jzp/UkTIg4o
            IbRa/pX44tPRRLw+vKkRuO2AjmKnpgVhTuC6zbWyBatkzh1Let75U22807A4gos=
            =UPfn
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
