apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mIZRcpVqCK/XSU6PlskaRq4cGUA=,iv:VdrO2zjrvo6JNQ+MsUOOPjcvP57hvHA5uh0JUA0420M=,tag:Kme13BLcUFANA2Eu2HKLsw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HjSN0F5iW1sKyd3b7+K7f7bcveV2uhUc9YEzWcm/Mgl1cZpMUWUFBg==,iv:rlRTV6dDyALX1Frp991yzdCBKTFYQJgvz+HHf8ZI6us=,tag:pyLiucDNK8hOuznAp8eAlg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:1sF63I+LRY1hR0e8mq173jiXoy2zq50uDQ==,iv:qrvmz9e9avJ9db4lh2OYRuy1wud5GxwjjFBC6jkPluI=,tag:OY29MxHevbuHcZYWJijIQA==,type:str]
sops:
    lastmodified: "2023-10-19T22:38:28Z"
    mac: ENC[AES256_GCM,data:PTiU0tqfSXphzphYWSy4hSwCZ6+r/BIeTEHdna+owmpBu2iBvmGGCAVX8McN0/uDUH2ckHiBu4blPZT8xmR4m5JLMI463l0sIatfkwPiRWHRo3lbLPZqf1Kvc3W7+abd1r0zUGqSCXLMdOvF05Tqcu1XQTso2UA2Ep4A0g/nC0I=,iv:qv5PFGZklWKkooBb43o7nfgeCO82kVbI6ke+IWYYFEE=,tag:DXpaRbawflb6aGWkEs3p1A==,type:str]
    pgp:
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/bebztrb33rKMMGbrz5CUXkV/1pj7mIToDL5UbASeE0WY
            KamoOiv0Hc8NjYgP1jEJaE6eYmrdRxWcSY1iQJwju3cQUsFMkXZULSZuyHUZULAK
            H9kj1KsfywLK5fiSc4ikS6bKRt5e7rWxAS0l6WNuHTWup4o4zhcCVS2L1O7X9GV6
            vjjDVACQl+MQryuCg3/71eJLD3sq/c+lq4whgMcqGUUhFEMeI+g1shqPPojqhrSU
            VQV8vcosceI1ydS8gOEgVi7URzAeisYO/PCoQjsxcdCH3giTF7IQl++Br1I4o1ag
            FhzX+EARHZYQpHJ3y5PeerpcB2cYEHChDR6esHAnudJeAZKc8Azl3SjdCQhafRtH
            QuDBvFDIKbPw70MvwKeaHBuT5DJDjI4crQtKiTol2OssAhkEyVOUUVXznOB+CmmX
            wZicsKray/4J/w3JSviEvOV8XerUYIXg4fj2Bfr9Mw==
            =Zi+D
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ/8COf5Wj6NJJ9CyY7OXccuZ2Nd5UOZ4+RZ7WgIZ6q6Tc0M
            c8MsK2OqTCv8TYYzgHu2YIwgl3QcQQGwv1995P7DVcqMff+XHVwcQ3NbaI5hjazz
            GJAZTLBcohYH6zINVQWMMaZVIfF4ZoEs87KBwysgSc4kIZilMZ9kF1rQcFMUtGXw
            4OCSnTXJ6eurqX68OBBej0Za20MDk1kK7DGTQKFfcHspfBkuwIJIAHeFZRZhFXPd
            0/LfahDXDZ56+3KaLeeIZl9Dj3oyBYWZR91e5BgIWfmYMFIuzQMbTV6D2ARk28MM
            RkOKFXox7zotwQP83dUAFJ50VBHFd7LgReUC8YCtM7oMWrzFQGAzc1ClIIBXEjXq
            gNkwfuc4Jotvau0iJQwYZgHQkYkj5qgqvB6scH19n48sxlyAjRFZmD7YAedd+IrG
            SRbwJ+QHzjp49lfj7iB+YIxSPJkmqNPPhdh7YipfsWnmqL4HQTSpkuNdg8UWyuEf
            k/t2dkqi4tD4wXPBLIheB1tJdUK1VQgKqE5ynqDGmsCEAPSox8fAA7dvNV8tswip
            piT30kYe1qoeHH+usjzmOuBQWQx2yYa2DA+TvPvdCdFwVni47Pho8rip3F8Sr7kb
            bcz2fFWR3nW4hS4THDC+AnIVD2WoqFq4aHnI3OAsEfs5aruocQlTbhEdeDkwrF3S
            XgFzy6Eu/Is25VT+jLJzCwEX7Zly25Ujts16xdxgG1RmYHHDIk75xEmdSxoF9Z0L
            +BYzxPGpZtEMdLT4VycQQ3pO/wUYLD6owMRenoRrjr0AOIcmP2IRXEsPs5UJL2I=
            =t2ky
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8ARAAluH5ti0SmOH/fEz+QqxGERQF6+nHwjyCVEpqwFpAElBj
            Kc0kF9FHVVKMPXdofIE/KZmwt4UxJzeQ8ME0PuSa6i9sXiMgOn13E8Pa6GlQDq1r
            nxDiwegX7/a+q1e6yThTZ7EN5NqPWOgdbbFtXrb7iLvEY50cRFjJGoLqQ+//xNHO
            jzNzLvkLc3iYoG2JExWYsnDxa+eEvUu7Z9VgFNT/EgFf7Pm+uinGo0HjDhW5skjC
            eMsX0A7ipoQHvpcRhXsAC/FORyIO0KaGDnOmgnxEA5LfyhbBJd+bSmk7p8G5u5Sk
            Gy90SSGiw7E1jRtj7YFKFGtWL4JXidU8Ha8ys1k5xaADn090nogY29y/jsaRpZ7q
            a0VyfXvyHrl3jwEvod6GgPLU4d1rU1CePDIjaRHBFypCA6Hx42XziqY8B+4t2yaH
            sOT+/D0M0hlYi3YrG3tS1XPTTxmkwjNL0zMBblzIVWpImA09uFig3o7wgNKl/fga
            pprqxGuZOIGJyiLd75iC9/Xcnl5Ny6GOP9iI75jucZjJioDkh4L/9+/GrvIr1/QK
            0R4NBVVdVO/GHLyTVwLFaea21hxX4KRANFcw7TWPkrVJMHDy3IjQoifOprJpXPMx
            RTW1AjsrGGblwmrz5e8I9tdQSnYvLNTSNf6HPWt5Go8URwTi8FzBeYwDRJPBhhDS
            XgHg+Nmv5HLkJT2EnER8iz99uTtibq4/qAjJxiZDDCOq9TDAphoPddMFJk1Sp7NH
            3tNrf17TJP0Zp6bRHenVCfAnDU9JHsBeEXi/MQsQ6k+ovmjC5V1JgxZW+pox5Yo=
            =dcoR
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdAdo0szOCpxfGcPs67xhPg9k3GxN8iAShWS2xAc3HRuy8w
            wliSDNA6L33CPHCpKhB7YT2NseUBzfKWKjiHHYzFzuWrfgBGOip9vujL3UJt++ht
            0l4BkM+eIpUffTLiqcL1JnESXIhSITa95JYqNwnRvNXjTKhHA2Ck8g3g3MtfHKx6
            SrOtYlfEDyq37HQcGYWuyQJq81MFg93+8CxWzw4EI8YiZVlMgH/7SrAWe65AU2qc
            =cAsr
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DrvgYWgvgiW4SAQdAs0hXwknYGhnCxjw300FAMOo7yJxksgCBg6wCyuuWAiQw
            /CKPXbyAdG/0LsDzZ7dATX9kuc4HbKtbZ5Fq7yX9RUMdRQXl/2JqaopvuvcXIXht
            0l4BiRdqd7cc1tWg7SkRtL8C5P6aZY/3hVO9zAeexcq2Ia57fva5swo3Sv8gSzLz
            k+/52E+YIySoFnH/zdTIObM2XA/aI6MGUCq0LqSZ7bY7GNSHytCU1ENBKh2IagH1
            =IKkB
            -----END PGP MESSAGE-----
          fp: F75CA0B534439722B612D343FAB6BD4E290CA406
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
