apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QsO2VA6d09CythzEwlKoDUdTI4FuqVkX,iv:8/9cP0O3H34mQ3j3W9PTAb8X1r9qthOgty2DO+wuYyA=,tag:ymkzQyeSQq1FL5QDo0HwyA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VIsNNff++k2fh6LRsajtumo9BrDVVWxD6v1nSoHUDC0=,iv:bBbCptxJuQS795+2kibE9w6rGwGzui3JsF4gRckRB5o=,tag:R35npn7bRg4cffaN8A7Snw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:xjLLTaYSJ3OcARKOYXEYn0hycUVWS3RBrQ==,iv:Qg6CegGzyvTb9TFqvngQaqFB5u6Ldq1sue0V1RkRoQM=,tag:TT5avI01SCJLozRR9Vgn5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-18T13:51:15Z"
    mac: ENC[AES256_GCM,data:Z58yI8Z3ERu9X26LYkDMfe5CUf1yuL564e/ZBhuEsuLfcEatacDfdP+DsD8xwZwAHPhMxnsquxkwcPgnk/GvFJh5iB6Znjtwbe/wngduH6E/eZ96C0lUT19dWNTApATokRcEsosWrQg5lXN2Ec86kK++MOSCDqqU90RzBsb0hb4=,iv:cuF6tV5KFmJuemZOVI5oWH9mZYbTcUAi6d862NPN5fQ=,tag:Tz5Nt9WAei4ljYn6/A4YcQ==,type:str]
    pgp:
        - created_at: "2022-08-10T19:13:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQgArcwsDK37Z9Md3bi0+xSrbC8YLoXjeLaH2uxYuRG2cosT
            WZb3lUtfkxg7iztXiuPGrxQzr2glUj9RUuVBHVSNxDjATWGdyS1v3vb1knQN+dPO
            n1/kKzdvRWSRm4OMSgAv7ovr8mpx7zcEzBk2Bs9oDeIMDg9FcnaMeKdAJz6c79hP
            VirUCrtlbmJwyicjNStVnaiRR32mPyyizqn0mZNFFILIdTzAPpFJbf0Qr3fAuow4
            RX/ylZ8ksG6osqhUWEf8blW8Jmm1TUE2aRQ167WvMrI1r/1S0t3PSKhy5dMypows
            VyJQfyTHVM/PirWDCnns8hZYloCgUTxMIfSLmXw8p9JeAZiJDvIcwTdw99i4GrzP
            Qg9/p0azge3z1EkC8JCWkhvMVExkRnLjpbY/JrUVAyLoJWDW7/HSTLyLqX83X+lC
            3jvTssUPX3dNcZ6zdTNS3JtvRMzWFyzEJkOD7btyDg==
            =W0of
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2022-08-10T19:13:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ//a9jyjjK5m0LkxIC1bx7cUur+Bu8ymUS/ISJHhQtocPKM
            189LMfjmU+bMC81sPl0HF7tmySFDFVHFOWb2EBjeP/HwYTat+UkqHTncgYnoUeC4
            NNpRTJpGfbZJ/BXbCGj5g6b8lQQpgd3TqrNMtm9OArLVJe8Jg2/FsjsHMR2qLuzu
            WIZVsQophwx52unJYQJb1zNuK4/GBmjcuV6YDzCdfAuZf0ZPT/9EMErbWSjS1GR/
            nU/9u0Az8DGjrvx9wkMC4KcN2fykCguyjSExZJ4LtqR/gCoUQiiSmnF3d0HxunoJ
            OyGlTTJwdfkdvg2brlZyjMiswBUyXF83Hv9UsZoATauPw2A83SaLGXnSoZeww92A
            fKwHmjoMybFaVaJtz53oy5VXikHcjEZeU7EHkCUQZHTKuZNGHF3GLrwudV4+rQFi
            xiHYrcJ8JQWvilj0mhBeW1MvCACNnBGT5T5aOkRCJ/qK6NAGjVN5q+tHTMggKq7C
            wLM6FgDOXqqdHzwnJayYEcMzgeUTvmJykuNbk15Fae/o8Iup5ihy+JU0X2JttRYL
            wnmeQ7NpegMbIcHh4S087Obu+2boEmtj7ULPxxCV3IgtJsZp7sQzWvgyTmCajVAO
            6ZX1p1BkGGVGCL+K5qElUwUgAH1Z0mqPuTglm2e/FT0UJVjrQWWlmh0bm9l/rh/S
            XgEnq8cTxHJnX6ck3DJV8VG5kMh70pWlKxEdH/pnqkyBG3KkY9tC2gJ6vI25wJEd
            a8nN53D50sY3xaIlMBLp5BtkFFQ6578sFHNU8lU9E0j4bIPTXKaX1o3bDYXPLMw=
            =p/Ab
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2022-08-10T19:13:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ//U19kp993bUk86eUyuoMWQUYLAo3P6LQQCQBi9I9q76Xd
            6v84g/OiJrid0sIa9VMAnDBz9jKOTTxnwMvX9ZAhCdL3WeSSw6P7PlRXt3rLrPzh
            Um/EBf0H9mxpJy9Mm36LT8DC4uGRy2neivISowPbCazDiioosy2qVWfsoSNL9SbB
            1Hpwg1CnmQSRcV3uuh6MAeFy5F1dDQgp5Ou5mCj5ApmZYWNNuPRN+zt85+WD884X
            CYte+Lu81hokNA1YxuxRcpGOl/swXiq3cWzhYdnf3wbo+kelqG7FAE4b+gfuY7y2
            PgK+1ulOzn1UgI3GicSD5yzQ52VOzMKj+C2ZSFqKGL/r4TZotEf6/afAbBVREy6d
            9cv76bg+sUWA1O4NQrS1dtXz9lXxA+eV8OcCRqsMI+9hQDx12Knp1rRAW7QS3sI8
            L+6694tw2m5Wjxm0qVLvv8D7Ec6uDaNvEf9ChWImOMhovXj6fTn6YLHmf+56g8Ro
            Oi9EdA4wMmCYNqzLYCrXhGk/jkvWgaaF11w+Q+olkPuMLmYNlxRldjZjzUFP/sH8
            85NxCsjaIsUAZhwd5DrvtMILP9c5u2XQ1jLXk+RE3Z94VQfRm+ZZwIOPMYZ2vExW
            0BcJ+1pioBw7l5PNPrSEPXc1TtOB539jK00JO/+gdl1lLrFnS0y+nt+Bf+s56nzS
            XgH+jlYu6nYzuOFiIzc2KApF+J1H9xG+VYCcyfNl4TBIFVHBtFVeHW79n8O73FcH
            H/EaMbH18gRkn65qj4kTrzNYXyNFjZ6MtaJk67aEryLiQw3+7aT8QmExkLvYNvo=
            =S5vU
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
