---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-data
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
