---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyter
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: quay.io/jupyter/datascience-notebook
              tag: '2024-05-27'
        pod:
          securityContext:
            fsGroup: 100
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "jupyter.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 8888

    persistence:
      files:
        existingClaim: jupyter-data
        advancedMounts:
          main:
            main:
              - path: /home/jovyan/work/
                subPath: work
              - path: /opt/conda/share/jupyter/kernels/pyscript
                subPath: pyscript-kernel
              - path: /usr/local/bin/start-notebook.d/
                subPath: start-notebook
              - path: /usr/local/bin/before-notebook.d/
                subPath: before-notebook
