version: "3.5"
services:
  vaultwarden:
    image: vaultwarden/server
    env_file: /homelab/vaultwarden/yubikey-api.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /homelab/vaultwarden:/data:rw
    networks:
      - webnet
    environment:
      - DOMAIN=https://bw.joshwolfe.ca
      - SIGNUPS_ALLOWED=false
    deploy:
      labels:
        - traefik.http.routers.bitwardenrs.rule=Host(`bw.joshwolfe.ca`)
        - traefik.http.services.bitwardenrs-service.loadbalancer.server.port=80

networks:
  webnet:
    external: true
