---
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/fluidd-core/fluidd
          tag: v1.31.2
ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
    hosts:
      - host: "fluidd.${domain}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
service:
  main:
    controller: main
    ports:
      http:
        port: 80
