---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: longhorn
