---
- name: Create root directory config
  file:
      path: '{{ config_dest_location }}'
      state: directory
      mode: '0755'

- name: Create directory structure for configs
  file:
      path: '{{ config_dest_location }}/{{ item.path }}'
      state: directory
      mode: '0700'
      owner: nobody
      group: nogroup
  with_filetree: '{{ config_src }}'
  when: item.state == 'directory'

- name: Template config files
  template:
      src: '{{ item.src }}'
      dest: '{{ config_dest_location }}/{{ item.path }}'
      mode: '0600'
      owner: nobody
      group: nogroup
  with_filetree: '{{ config_src }}'
  when: item.state == 'file'
