---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/common-3.7.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
    controllers:
      app:
        enabled: true
        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.8
            restartPolicy: Always

          gluetun:
            dependsOn: dnsdist
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_PORT_FORWARDING: on
              PORT_FORWARD_ONLY: on
              SERVER_COUNTRIES: Netherlands
              WIREGUARD_PRIVATE_KEY: ${vpn_proton_wg_private_key}
              FIREWALL_INPUT_PORTS: 8080
              DOT: 'off'
              DNS_ADDRESS: 127.0.0.2
              TZ: America/Toronto
            restartPolicy: Always
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.1
            env:
              PUID: 568
              PGID: 568
            securityContext:
              runAsUser: 568
              runAsGroup: 568

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: 8080
              CRON_ENABLED: true
              CRON_SCHEDULE: '*/5 * * * *'
              LOG_TIMESTAMP: true

    service:
      app:
        controller: app
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "qb.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
    persistence:
      config:
        existingClaim: qbittorrent-config
        advancedMounts:
          app:
            app:
              - path: /config
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/Downloads
        advancedMounts:
          app:
            app:
              - path: /downloads
      tun:
        type: hostPath
        hostPath: /dev/net
        hostPathType: Directory
        advancedMounts:
          app:
            gluetun:
              - path: /dev/net/tun
                subPath: tun
      dnsdist:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          app:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true

      port-forward-config:
        type: emptyDir
        advancedMounts:
          app:
            port-forward:
              - path: /config
