---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/common-3.7.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3
            securityContext:
              runAsUser: 568
              runAsGroup: 568

          gluetun:
            dependsOn: main
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            # -- environment variables.
            # See [image docs](https://github.com/qdm12/gluetun-wiki) for more details on how to configure
            # your VPN and how to set up port-forwarding.
            env:
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_PORT_FORWARDING: on
              VPN_SERVICE_PROVIDER: protonvpn
              SERVER_COUNTRIES: Netherlands
              WIREGUARD_PRIVATE_KEY: ${vpn_proton_wg_private_key}
              FIREWALL_INPUT_PORTS: 8080
              DOT: 'off'
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.0"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: "/tmp/gluetun/forwarded_port"
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "qb.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    persistence:
      # Configure an emptyDir to share the port-forwarding location between containers
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
      config:
        existingClaim: qbittorrent-config
        advancedMounts:
          main:
            main:
              - path: /config
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/Downloads
        advancedMounts:
          main:
            main:
              - path: /downloads
