---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ale-pal
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/wolfecub/ale-pal
              tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "ale.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

# persistence:
#   config:
#     existingClaim: ale-config
#     globalMounts:
#       - path: /config
#         readOnly: false
