---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: receipt-wrangler
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          api:
            image:
              repository: noah231515/receipt-wrangler-api
              tag: latest # TODO: App only publishes latest 🤮. Need to get a versioned container
          ui:
            image:
              repository: noah231515/receipt-wrangler-desktop
              tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "receipt.${domain}"
            paths:
              - path: /api
                pathType: Prefix
                service:
                  identifier: api
          - host: "receipt.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: ui
    service:
      api:
        controller: main
        ports:
          http:
            port: 8081
      ui:
        controller: main
        ports:
          http:
            port: 80
