---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phantombot-config
  namespace: misc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
