---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: phantombot
  namespace: misc
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gmt2001/phantombot-stable
      tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: localOnly@file
        hosts:
          - host: "phantombot.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 25000
    persistence:
      data:
        enabled: true
        existingClaim: phantombot-config
        mountPath: /opt/PhantomBot_data
    podSecurityContext:
      fsGroup: 568
    env:
      PHANTOMBOT_PANELUSER: "${phantombot_web_username}"
      PHANTOMBOT_PANELPASSWORD: "${phantombot_web_password}"
      PHANTOMBOT_DISCORD_TOKEN: "${phantombot_discord_token}"
      PHANTOMBOT_USER: "${phantombot_channel}bot"
      PHANTOMBOT_CHANNEL: "${phantombot_channel}"
      PHANTOMBOT_USEHTTPS: "false"
