version: "3.5"
services:
  server:
    image: ghcr.io/wolfecub/starbound:latest
    ports:
      - 21025:21025
    volumes:
      - /homelab/starbound:/starbound/storage
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple
