version: "3.5"
services:
  traefik:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /storage/homelab/traefikconfig/traefik.toml:/traefik.toml
      - /storage/homelab/traefikconfig/acme.json:/acme.json
    labels:
        - traefik.backend=traefik
        - traefik.frontend.rule=Host:traefik.house20.ca
        - traefik.docker.network=webnet
        - traefik.port=8080
    networks:
      - webnet
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  heimdall:
    image: linuxserver/heimdall:latest
    volumes:
        - /storage/homelab/heimdallconfig:/config
    labels:
        - traefik.backend=heimdall
        - traefik.frontend.rule=Host:heimdall.house20.ca
        - traefik.docker.network=webnet
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
    networks:
      - webnet
    ports:
      - 1234:80
      - 1235:443

  plex:
    image:  linuxserver/plex:latest
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    networks:
      - webnet
    volumes:
      - /storage/homelab/plexconfig:/config \
      - /storage/media/tv-shows:/data/tvshows \
      - /storage/media/movies:/data/movies \
    labels:
      - traefik.backend=plex
      - traefik.frontend.rule=Host:plex.house20.ca
      - traefik.docker.network=webnet
      - traefik.port=32400

  sonarr:
    image:  linuxserver/sonarr:latest
    ports:
      - 8989:8989
    networks:
      - webnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/media/tv-shows:/tv
      - /storage/homelab/sonarrconfig:/config
      #- /storage/homelab/nzbgetdownloads:/downloads
    labels:
      - traefik.backend=sonarr
      - traefik.frontend.rule=Host:sonarr.house20.ca
      - traefik.docker.network=webnet
      - traefik.port=8989

  radarr:
    image:  linuxserver/radarr:latest
    ports:
      - 7878:7878
    networks:
      - webnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/media/movies:/movies
      - /storage/homelab/radarrconfig:/config
      #- /storage/homelab/nzbgetdownloads:/downloads
    labels:
      - traefik.backend=radarr
      - traefik.frontend.rule=Host:radarr.house20.ca
      - traefik.docker.network=webnet
      - traefik.port=7878

  jackett:
    image:  linuxserver/jackett:latest
    ports:
      - 9117:9117
    networks:
      - webnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/homelab/jackett/config:/config
      - /storage/homelab/jackett/downloads:/downloads
    labels:
      - traefik.backend=jackett
      - traefik.frontend.rule=Host:jackett.house20.ca
      - traefik.docker.network=webnet
      - traefik.port=9117

networks:
  webnet:
    external: true
