version: "3"
services:
  plex:
    image:  linuxserver/docker-plex:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
    volumes:
      - /storage/plexconfig:/config \
      - /storage/media/tv-shows:/data/tvshows \
      - /storage/media/movies:/data/movies \
networks:
  webnet:
