version: "3"
services:
  plex:
    image:  linuxserver/plex:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    networks:
      - webnet
    volumes:
      - /storage/plexconfig:/config \
      - /storage/media/tv-shows:/data/tvshows \
      - /storage/media/movies:/data/movies \
networks:
  webnet:
