version: "3.5"
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    networks:
      - hostnet
    volumes:
      - /homelab/homeassistant:/config
    environment:
      - TZ=America/New_York
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple

  hassconfigurator:
    image: causticlab/hass-configurator-docker:x86_64
    networks:
      - webnet
    volumes:
      - /homelab/hassconfigurator:/config
      - /homelab/homeassistant:/hass-config
    environment:
      - TZ=America/New_York
    deploy:
      labels:
      - traefik.http.routers.hassconfig.rule=Host(`hassconfig.${domain}`)
      - traefik.http.routers.hassconfig.tls=true
      - traefik.http.services.hassconfig-service.loadbalancer.server.port=3218
      placement:
        constraints:
          - node.hostname == shirleytemple

  #mosquitto:
  #  image: eclipse-mosquitto
  #  networks:
  #    - hostnet
  #  volumes:
  #    - /homelab/mosquitto:/mosquitto
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == shirleytemple

  nodered:
    image: nodered/node-red:latest
    networks:
      - hostnet
    volumes:
      - /homelab/nodered:/data
    environment:
      - TZ=America/New_York
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple

  esphome:
    image: esphome/esphome
    networks:
      - hostnet
    volumes:
      - /homelab/esphome:/config
    environment:
      - TZ=America/New_York
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple

networks:
  hostnet:
    name: "host"
    external: true
  webnet:
    external: true
