version: "3.5"
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    networks:
      - hostnet
    volumes:
      - /homelab/homeassistant:/config
    environment:
      - TZ=America/New_York

networks:
  hostnet:
    name: "host"
    external: true
  webnet:
    external: true
