---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.11.17
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 5m
  values:
    server:
      retentionDiskSpaceUsage: 15GB

      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - name: "logs.${domain}"
            path: /

    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
