---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
