---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
