---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: home
  labels:
    recurring-job-group.longhorn.io/daily: enabled
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
