---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: admin
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com
      chart: authelia
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: authelia/authelia
      tag: 4.31.0
    pod:
      env:
      - name: TZ
        value: America/Toronto

      extraVolumeMounts:
      - name: authelia-users
        mountPath: /config
      - name: authelia-persist
        mountPath: /data

      extraVolumes:
      - name: authelia-users
        configMap:
          name: authelia-users
          items:
            - key: users_database.yml
              path: users_database.yml
      - name: authelia-persist
        hostPath:
          path: /homelab/authelia

    domain: "${domain}"

    ingress:
      enabled: true
      subdomain: login
      tls:
        enabled: false

      traefikCRD:
        enabled: true
        entryPoints: [web, websecure]

    configMap:
      default_redirection_url: "https://${domain}"

      totp:
        issuer: "${domain}"

      authentication_backend:
        disable_password_reset: true
        ldap:
          enabled: false
        file:
          enabled: true
          path: /config/users_database.yml

      access_control:
        default_policy: deny
        rules:
          ## Rules applied to everyone
          - domain: "*.${domain}"
            policy: two_factor

      session:
        domain: "${domain}"
        redis:
          enabled: false

      storage:
        local: 
          enabled: true
          path: /data/db.sqlite3
        postgres:
          enabled: false

      notifier:
        smtp:
          enabledSecret: true
          host: ${authelia_smtp_server}
          port: 587
          sender: ${authelia_smtp_email}
          username: ${authelia_smtp_email}

    secret:
      jwt:
        value: ${authelia_jwt_secret}
      smtp:
        value: ${authelia_smtp_password}
