---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.0.3
            securityContext:
              fsGroup: 568
              runAsUser: 568
              runAsGroup: 568
            env:
              TZ: America/Toronto

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "radarr.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    service:
      main:
        controller: main
        ports:
          http:
            port: 7878

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media
        globalMounts:
          - path: /media
            readOnly: false
