version: "3.5"
services:
  duplicati:
    image: linuxserver/duplicati
    networks:
      - webnet
    volumes:
      - /homelab/duplicati:/config
      - /homelab:/source
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    deploy:
      labels:
        - traefik.http.routers.duplicati.rule=Host(`backup.${domain}`)
        - traefik.http.routers.duplicati.tls=true
        - traefik.http.services.duplicati-service.loadbalancer.server.port=8200
        - traefik.http.routers.duplicati.middlewares=authelia@file

networks:
  webnet:
    external: true
