apiVersion: v1
stringData:
    domain: ENC[AES256_GCM,data:3JV4a6tysLdNzg==,iv:l1TAey3BSL/OThNs90dYOKtAiBpDbyYHsBqINzvV9qM=,tag:Yl763LtPwmoh1jotE4RUUg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets-argo
    namespace: argocd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exexc7wwauqfja4j85n4hrc2rwgvvcykl9xv9y2rdhlvk5x653rqxs980a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETk16VzRwUVVKVGpwZ2hp
            UVlkcUtMb3lPajFSa0syUkpET1VGV2FqQUVZCjk5bzJYc0x4MjdIZnE4TWZqU3Fz
            NDhWT0I4NmxON3BmSlVua1BNVnZjOTAKLS0tIENYcGptdFpMNEkxa1dvbjByNW8r
            MjVhSG9NTWtyOW9JRWZMSmtiVkxRWUUKQ640H/pltieD6uTFAFm0fmgXTdG0L0o/
            w9MBf1jKYKP4hCY0qyn8r1TOoy3Wnj8Uxs5bbzU1V6+StnR6O5mwSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T20:35:37Z"
    mac: ENC[AES256_GCM,data:6FREMcHr9EZgnM3hhnU9bxcsudz/x1PMYX3Yhz9AKpb85+J0Gt0QzMDYJ9WOke6QmBK8jg2YG10Mircf07v9urwZmRAv7qlPo2iCfRo2iJqPsBmD03BviXyc8eOmHdvzum65qgFkNlz522Vs8+dxy14Ozy+NjSCFcTPoIH37lBk=,iv:VbDvPwH53wOfuNZu83MzovBsMSGTivr+Lgd/CELdN6E=,tag:wLH4rbXB5ekciFSbyq2zQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
