data:
    domain: ENC[AES256_GCM,data:Dk3bXPg3Jw==,iv:uG+KGmYbZSaSgabRMk3Li2hOAR6crk14VHqJxLYc8Vg=,tag:B2PY9M/ojyMYmvUT8SNffw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-17T04:17:55Z"
    mac: ENC[AES256_GCM,data:nYC6l4DdnceqsjWYJkw/h9FrN3PeEtcTJR9DE5mOgmwGFndK+TZpKwTFH8AXwVedTvcVJ4pDXOh/vBgaDX72irHWGuuLRdiLLvzKF03riXTUi4y33QYg/TG4ZVawzId33xlG+Lrz2wQJajx4UEzbJBnZTLBTN6TK6XbPqA++uaU=,iv:4bYbKpfmgIyop55cZexKToZ9QZGkSyhJ6yyI1s3b+Fg=,tag:pG9938Zx+BRHDduQLWpMgA==,type:str]
    pgp:
        - created_at: "2024-12-17T04:17:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf8CQZlGS2iJnb9zLJoJ+gd6OGXdJOoMxvD7OpZwb5ktEif
            HO+cZ8NDeTlZZ9W9pQ6gYnXcGzOwNU9TuR5oLLafOgT7C7sErFYmYMHpPxdM5+dh
            K/WrxN6SqjELYQP9Mo64nEfWZ5e2NETmwarSBjv+nC9eOG07YyJh+1S4zhw9x0MT
            lR+O7T8DgJMvJ4hZFsvK27p2pT2AK2NZAwpGx6GZt+Jg9XNGq2pEYlpbvcvg/d9b
            mw9YcZOPp7M5nSSPJsFXKSxFHsCTzpns4+5vFJuXSXiJdTgXlTGCTZYWEc4549bA
            KU90+1HPh/7nEd0DYFyVMlOrC43xrX/WNfAGdPZtZdJeAcNc7uNepsBHv53aRLHM
            2haN1deiK+zo2MnQvd8z5qHPg2YGuC2FiiX2And9m8agGtzaBQeAR285faMMbdvL
            CeNPnjpgbkv1l+8Kq5zHj+iwIOlJtAAF1dSIgOiqDA==
            =a+MF
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2024-12-17T04:17:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ/+LGzokSqshOzO8UvOamUqq/GdfFIXoXUIujIWAjCOe71U
            nsg00w9RKsJuc4fbOv9091u6Ieqv+ECjhfnCwmG4+s8WKt4JnfbcZfjhRWLhg78z
            iZ+Z2SKRrbxLEkg3quImcNNxDwK+qlRE0OnPZRTzNuT/nH3Mdh4P+W4zvmXKgtoM
            agIeWG3sKMfhHgrdNYTiZEucX2eYGGsQpjiP+k7c3dS5IYflI8gf1QI3ohOe14d1
            pcOn7O5sUyyqrOJPQ63NjDTdBA+Jd0pD1TCiuCcoB5XZwpIdVHjp9tkWR5BkZCz6
            Q4kHE8uotuQjwz+GCGBuQnM23gFm94Py0qFTnWj9wFFq45WbH3Onn0Eizb+tnATd
            2QSEuD4E/hpJcwh1R1LPcRbJEuU07L88yjMTLvvCZ+NOVY6yYWjl/9bxVQvbkX37
            IeUYVj/PCYlCTJSPhdvqFFBT7U668/ildq3+2xNnLccIjFOg8K/u0oKovwYhj1pM
            fPzHU84L7sphuhFd+pI1lVpEgcWrqhqbjt48AccohcGRTBSdTqB0lZ+e7E5CaXcN
            IYnCXuB9xOlobK7tnJA2jdsxkSNsrecD/LTXKB/xX+wUSWQvxLc3DuXL0GYOehgx
            xGWtdPKuVEVtxrs5u+g5QS1K3LUg4xweHM+qGzzWqnKzBMp1KJGZ1XU9j+qh/bfS
            XgFPPT3Dkfy8HYFhXAROHJv6hJi9aTttHEorfuS5sG0P1QMNentpyLGtxNsZEfeg
            1QB5eVXHDWWqvWG33qbzakThcR6N7HoaqF//gfENnnKu88ncUKI+tjxFpZ5MIzM=
            =CYBX
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2024-12-17T04:17:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ//dyIxhf07hG4zAWOq57MCIg4s52lnQNTOnf+y+lrG2fvV
            7xBTjPYaUMqPj2YqLRLYpbKYTTHVsiRs1WsfAsjf1u6MZn1ixXVHhNIBQzeqD65S
            pEASudf4Gurw2w7gxTf7vobhLZ9YnSIUBvSkZkFhYWTwEjpBmRz6k5x9VzZB63fM
            lK7A9+L6PT1TzESEuf1mFqPYml9LmEgE8Y+YQ8Qazh2rby87ZkoFlMR8eTrykjh7
            lVoy51exve6gIX03uHBHtuKpExgYMPHzqGTG1nXxRqnSaUmkWTvq60f9A/hk+e2+
            vRlJodMgj8WRT2KjPABTCjQv8tIW0Aj1csCkQ3GEfStzMg3XtaH7WdSeuer3FLF1
            ZNg6AhrGod3pIznhde0V7Psd4WD5JOEvDgaFlFLT6zbpJBXMn2oAnPakyeBO5tbm
            C9LX0HtrDtKIp4NY02SpKA/O4MVFsz+NqIF0F7QWECf0orB9wLxr2pHdg9rkAlef
            b2vbIZB+8WwCKaJEROXGS01KSl2+aTc2I2HpDYmBc66XTrZl/K1RIkEAFIdkQSev
            ZzXAnXTolYHG2mZbuRAyagGY47CCd4tdaUIEYXmxdhLXh9tIAs+INk3K/M0/P6UG
            bM2xXju3pWXEmr7oZgEd5sgNrvkDlaSE8Q7Mjo2+yTt0Pkv8mTGJWU3CMLn+i23S
            XgGq9c4oV3f8U+xqdNhXZxPa7YZpkwduOU7cUU2ErS5XEMJKfvhP2qjZJ+rowwo0
            yi64jz6vKZkTuFuyn7bHN670elEhZrNy8RP6EmEbLQsWTmOLNNTKP/MSBm+5TnY=
            =i9fn
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
