apiVersion: v1
kind: Secret
data:
    domain: ENC[AES256_GCM,data:c00cyU2N779sPQ==,iv:vImjPmGigrfhGXDzCBQ/6ap/DCyyIRaGYMJmdsooMCA=,tag:OlIx5KtvgwAxpwZmUnS9eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exexc7wwauqfja4j85n4hrc2rwgvvcykl9xv9y2rdhlvk5x653rqxs980a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VmVKMFF2ZHBZREtsQnVv
            QnV2Mk41anBiTnlyWkhaYWl4NE9FZ2FmS1NvCi9oTGdzeE1zR1c2VXVkWVdwaVJC
            RlV1dWJMbzIrUVlTYVR1dFJLRGZRdGMKLS0tIEJDbFhIVk1xcHZRYnZyRUg3dm9i
            aHAweWE4Q3ZSeDdZSzBtMzFBZWU1amMKSfbRfz1aM33wtN1tDCbHCN0s7MnjTJ8g
            NH5LTx6UZHXwUGug0FgILAYJQQxzFYlDDLQU6mKZIELGsrsaxwrW/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T21:19:41Z"
    mac: ENC[AES256_GCM,data:9QTrKkddPAzgMll0uzDR2WAAjmxInVRmFmWfwYlA903xgZwLfJGJKkuebHtkfQZH2T+R+ph2SNcUza4HFzxZNfC0/ewcaV3Iyk6SGJHmjhjTvhY+8F5xVMcULVy1l6mkITGwF94Kpxt3VBSpQ7Vp8y7R2LgFOXXn/wUTinGzn1A=,iv:L0ljk0W991Hc5RBpWd1qNRqhZxd+HfoojZ39nVRD8+k=,tag:o2cKcmmfcrLko3q+5inpNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
