version: "3.5"
services:
  traefik:
    image: traefik:v2.2.1
    depends_on:
      - authelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homelab/traefik:/etc/traefik
    networks:
      - webnet
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    env_file: /homelab/traefik/compose.env

  shepherd:
    image: mazzolino/shepherd
    networks:
      - webnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/wolfe/.docker/config.json:/root/.docker/config.json
    environment:
      - FILTER_SERVICES=label=shepherd.enable
      - WITH_REGISTRY_AUTH=true

networks:
  webnet:
    external: true
