---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
      interval: 5m
  values:
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
      services:
        - Misc:
            - YouTube:
                icon: youtube.svg
                href: https://youtube.com
            - GitHub:
                icon: github.svg
                href: https://github.com
        - Homelab:
            - Vaultwarden:
                icon: vaultwarden.svg
                href: https://vaultwarden.${domain}
            - Home Assistant:
                icon: home-assistant.svg
                href: https://hass.${domain}
            - Frigate:
                icon: frigate.svg
                href: https://frigate.${domain}
        - Media:
            - Plex:
                icon: plex.svg
                href: https://plex.${domain}
            - Sonarr:
                icon: sonarr.svg
                href: https://sonarr.${domain}
            - Radarr:
                icon: radarr.svg
                href: https://radarr.${domain}
            - Transmission:
                icon: transmission.svg
                href: https://transmission.${domain}
            - Readarr:
                icon: readarr.svg
                href: https://readarr.${domain}
            - Prowlarr:
                icon: prowlarr.svg
                href: https://prowlarr.${domain}

      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
      kubernetes:
        mode: cluster
      settings:

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "homepage.${domain}"
            paths:
              - path: /
                pathType: Prefix
