---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: koenkk/zigbee2mqtt
              tag: 2.1.3
            env:
              TZ: America/Toronto
              ZIGBEE2MQTT_DATA: /data
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/zigbee
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://${mqtt_ip}
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
              # DEBUG: "zigbee-herdsman*"
            securityContext:
              privileged: true
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - docker02

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "zigbee.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    persistence:
      data:
        enabled: true
        existingClaim: zigbee2mqtt-data

      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_7ec5690d65afed11a1253d4e71c9e8b5-if00-port0
        advancedMounts:
          main:
            main:
              - path: /dev/zigbee
