---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.22.1
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "zigbee2mqtt.${domain}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        existingClaim: zigbee2mqtt-data

      usb:
        enabled: false
        type: hostPath
        hostPath: /dev/ttyACM0
        mountPath: /dev/ttyACM0

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - docker01

    securityContext:
      privileged: true

    config:
      homeassistant: true
      permit_join: false
      mqtt:
        server: "mqtt://mosquitto"
      serial:
        port: /dev/ttyACM0

    env:
      TZ: America/Toronto
