---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.19.1
    hostNetwork: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: "zigbee2mqtt.${domain}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        existingClaim: zigbee2mqtt-data

    additionalVolumeMounts:
      - name: usb
        mountPath: /dev/ttyACM0

    additionalVolumes:
      - name: usb
        hostPath:
          path: /dev/ttyACM0

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - screwdriver

    securityContext:
      privileged: true

    config:
      homeassistant: true
      serial:
        port: /dev/ttyACM0

    env:
      TZ: America/Toronto
