---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
  namespace: admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
