repositories:
- name: k8s-at-home
  url: https://k8s-at-home.com/charts
- name: k8s-at-home-common
  url: https://library-charts.k8s-at-home.com
- name: traefik
  url: https://helm.traefik.io/traefik
- name: bedag
  url: https://bedag.github.io/helm-charts/
- name: authelia
  url: https://charts.authelia.com
- name: utkuozdemir
  url: https://utkuozdemir.org/helm-charts

bases:
- environments.yaml

---

helmfiles:
  - path: helmfiles/*/*.hf.yaml
    values:
    - {{ toYaml .Values | nindent 6 }}
