version: "3.5"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /homelab/homeassistant:/config
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host
