---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
