---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
      hosts:
        - host: "flux.${domain}"
          paths:
            - path: /
              pathType: Prefix
    adminUser:
      create: true
      passwordHash: $2a$10$MBVDcBxKlbqMVB8kt0ixCOVegvxjoreXpi6O.CU0lFNQOMxr0p65S
      username: admin
