version: "3.5"
services:
  hugo:
    image: ghcr.io/wolfecub/blog
    networks:
      - webnet
    deploy:
      labels:
        - traefik.http.routers.joshwolfe.rule=Host(`${domain}`)
        - traefik.http.services.joshwolfe-service.loadbalancer.server.port=80
        - shepherd.enable

networks:
  webnet:
    external: true
