---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbootxyz
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/netbootxyz
      tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "netboot.${domain}"
            paths:
              - path: /
                pathType: Prefix
          - host: "netbootassets.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: netbootxyz-http-assets
                  port: 80

    service:
      main:
        ports:
          http:
            port: 3000
      http-assets:
        enabled: true
        primary: false
        type: ClusterIP
        ports:
          http-assets:
            enabled: true
            primary: false
            protocol: HTTP
            port: 80

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: netbootxyz-config
      assets:
        enabled: true
        type: custom
        mountPath: /assets
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/k8s-shared/netbootxyz
    podSecurityContext:
      fsGroup: 568
