---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbootxyz
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/netbootxyz
      tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "netboot.${domain}"
            paths:
              - path: /
                pathType: Prefix
          - host: "netbootassets.${domain}"
            service: httpAssets
            paths:
              - path: /
                pathType: Prefix

    service:
      main:
        ports:
          http:
            port: 3000
      httpAssets:
        ports:
          http:
            port: 80

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: netbootxyz-config
      assets:
        enabled: true
        type: custom
        mountPath: /assets
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/k8s-shared/netbootxyz
    podSecurityContext:
      fsGroup: 568
