---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoolman-data
  namespace: printer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
