---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
  namespace: home
data:
  config.yml: |
      tls:
        enabled: False

      mqtt:
        host: ${mqtt_ip}
        port: 1883

      database:
        path: /data/frigate.db

      go2rtc:
        streams:
          backdoor: rtsp://admin:${camera_password}@192.168.2.4:554/Preview_01_main
          driveway: rtsp://admin:${camera_password}@192.168.2.5:554/Preview_01_main

      detectors:
        coral:
          type: edgetpu
          device: usb

      motion:
        mask:
          - 0.997,0.027,0.999,0.007,0.805,0.006,0.806,0.03 # Timestamp

      cameras:
        frigate_backdoor:
          ffmpeg:
            inputs:
              - path: rtsp://localhost:8554/backdoor
            hwaccel_args: preset-vaapi
            output_args:
              record: preset-record-generic-audio-copy
          detect:
            enabled: True
          objects:
            filters:
              person:
                min_area: 120000

        frigate_driveway:
          ffmpeg:
            inputs:
              - path: rtsp://localhost:8554/driveway
            hwaccel_args: preset-vaapi
            output_args:
              record: preset-record-generic-audio-copy
          detect:
            enabled: True
          review:
            alerts:
              required_zones:
                - driveway
          snapshots:
            required_zones:
              - driveway
          zones:
            driveway:
              coordinates: 0,1,1,1,1,0.099,0.67,0.061,0.661,0.187,0.58,0.16,0.393,0.187,0.38,0.203,0,0.324
          objects:
            filters:
              person:
                min_area: 38000

      record:
        enabled: True
        retain:
          days: 3
          mode: all
        events:
          retain:
            default: 30
            mode: active_objects

      snapshots:
        enabled: True
        crop: True

      birdseye:
        enabled: True
        mode: continuous
