---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
  namespace: home
data:
  config.yml: |
      mqtt:
        host: ${mqtt_ip}
        port: 1883

      database:
        path: /data/frigate.db

      go2rtc:
        streams:
          backdoor: rtsp://admin:${camera_password}@192.168.2.4:554/Preview_01_main
          driveway: rtsp://admin:${camera_password}@192.168.2.5:554/Preview_01_main

      detectors:
        coral:
          type: edgetpu
          device: usb

      cameras:
        frigate_backdoor:
          ffmpeg:
            inputs:
              - path: rtsp://localhost:8554/backdoor
            hwaccel_args: preset-vaapi
          detect:
            enabled: True
        frigate_driveway:
          ffmpeg:
            inputs:
              - path: rtsp://localhost:8554/driveway
            hwaccel_args: preset-vaapi
          detect:
            enabled: True
          record:
            events:
              required_zones:
                - driveway
          snapshots:
            required_zones:
              - driveway
          zones:
            driveway:
              coordinates: 0,2160,3840,2160,3840,72,2546,182,1477,226,0,486

      record:
        enabled: True
        retain:
          days: 0
          mode: all
        events:
          retain:
            default: 30
            mode: active_objects

      snapshots:
        enabled: True
        crop: True

      birdseye:
        enabled: True
        mode: continuous
