---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.16.1
            securityContext:
              privileged: true
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - docker04
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "frigate.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
          - host: "go2rtc.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: go2rtc
    service:
      main:
        controller: main
        ports:
          http:
            port: 5000
      go2rtc:
        controller: main
        ports:
          http:
            port: 1984

    persistence:
      config:
        existingClaim: frigate-config
        globalMounts:
          - path: /data
            readOnly: false
      config-file:
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 1.5Gi
        globalMounts:
          - path: /dev/shm
      media:
        type: nfs
        server: "${storage_host_ip}"
        path: /raid/k8s-shared/frigate
        globalMounts:
          - path: /media
      quicksync:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
      usb:
        type: hostPath
        hostPath: /dev/bus/usb
        hostPathType: Directory
        globalMounts:
          - path: /dev/bus/usb
