---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.13.2@sha256:2906991ccad85035b176941f9dedfd35088ff710c39d45ef1baa9a49f2b16734

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "frigate.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
          - host: "go2frig.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: go2rtc
    service:
      main:
        controller: main
        ports:
          http:
            port: 5000
      go2rtc:
        controller: main
        ports:
          http:
            port: 1984

    persistence:
      config:
        existingClaim: frigate-config
        globalMounts:
          - path: /data
      config-file:
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /dev/shm
      media:
        type: nfs
        server: "${storage_host_ip}"
        path: /raid/k8s-shared/frigate
        globalMounts:
          - path: /media
