data:
    docker_host_ip: ENC[AES256_GCM,data:B16QNAIiwAqW4wWAbA==,iv:6cEBUdwFLc+JTsoFkKn35FuppfYyYFVEvVbYgVkzN3Q=,tag:R9qZUokUXEnScPLzIkORuw==,type:str]
    domain: ENC[AES256_GCM,data:UkUHheT6sxkxiqKA,iv:A1l1/wC7GFFU88QykqBkQlAEb1/Pk6IDBaQtwTlnV1g=,tag:7fwN1Blbcuuvk/MiDddy7w==,type:str]
    email: ENC[AES256_GCM,data:Du2Eynm0jUPHnh9TlUv9BJO3u4gN9g==,iv:uoG0EVDgmGShTMq80P+QKMqUVsqO1JtSlUA/xTTPnC4=,tag:ixmXZcx/SW5e/yRqLi3pYg==,type:str]
    network_subnet: ENC[AES256_GCM,data:JrmALsqLwCVPv/1RzuU=,iv:gYfghaIv5tUzCNf7ULOaLyNS8Dji3gext+jPH+NeiU8=,tag:YfAKWLSpD28hihXinUTw1Q==,type:str]
    storage_host_ip: ENC[AES256_GCM,data:C5mQ8mkTZrtaf1VGpg==,iv:b/vFqvtzWuNSfOKcZk0wTuv5IWK/vCdda0H3U3EEtfI=,tag:Nj0JPfOIn21/xFt6V5sxWQ==,type:str]
    traefik_basic_auth_credentials_hash: ENC[AES256_GCM,data:fGqhjyoUdb+PxIuf+/xoWEDbSJh7ZRIQolRgHIi3pCrXuL/gNfrxhiAHty0r8fWzZb5QkuN4X2tjBI4wbBLYRA1T,iv:OgIv2bH1ZqRGFLxodBmovd5DRUPTua8Lucx/DyGycr8=,tag:SpCZ/T/y7V3A4m81dcYK8w==,type:str]
    #ENC[AES256_GCM,data:H8/L1CSBCIJUrM7dY1/M8FrxRUPtp+4T5JV7PVbVonEnqYF6PtcM49dcqcEA58pD8LZ2WCMs9g==,iv:HB1zNm6V/rtipN9ZFrRngI5KkchzsQ0F6A0g7xxUiwk=,tag:fXvf2Cw9jS4BZlX9chnBPA==,type:comment]
    authelia_jwt_secret: ENC[AES256_GCM,data:ifW7xsbARC2w6CCHHjzdP7drFJd3j2LywPEtgfYmwzg=,iv:zU7ep2Er9i9XFTKkay39HGuuWxJUfmMytjjt2APtomE=,tag:KGxZA/F9k5mt2FW2vrEQmw==,type:str]
    authelia_smtp_email: ENC[AES256_GCM,data:YE0E+MwVl/b3mx3bxjwDOM+KRYavULsP9Jk=,iv:AkRoTtwmyYyd2VQZD1K2kVXGfPjQmVDC/S1yr0JHJ8M=,tag:abDW4f/3eaGHKtgb1jDezA==,type:str]
    authelia_smtp_password: ENC[AES256_GCM,data:nPd1EGzkUEdjqWUvebwnZgbJjOU=,iv:4ZMyTgPB7j/eLjmibLG8uXT4J0Ryz1gVDo5oaZr2Aas=,tag:X48Qns3OdTRfM90DdT8eVg==,type:str]
    authelia_smtp_server: ENC[AES256_GCM,data:vYUqqD54ilMtyykOUQ==,iv:kkxYpB7UHzZO5JvkGPKdBkWPBHfpfl4TVIQdx1aFdno=,tag:Kks0DE+3JWBmbzxjKEYuOw==,type:str]
    authelia_primary_email: ENC[AES256_GCM,data:dL65q9IupMMX/b+NR1DPGiY82pgbWA==,iv:8rUBv9GP2LvD2VkLvL+fOkdqUaEuo9LWFAELTCdxeZg=,tag:GpTYtxCvv068xQHhqTbHQw==,type:str]
    authelia_primary_password_hash: ENC[AES256_GCM,data:NzIGN0wFDoc/LJIIKnch9Umve9AYvWOP8JSwM3Ri20Q7Pit6kkYYzwakWWppAAO/GWe0Y0lOj+FZTdTgb6mZbbSLrlVtn4i9b5DCeHB8xUY648a/ya2kjF8bIk8MczGg4A==,iv:u5xq+D3Jp9QHkVS4Wtdj6eawgWGB6RasR5wquikhcDI=,tag:euE5LiWnGo2R9t/f12YUrg==,type:str]
    authelia_primary_username: ENC[AES256_GCM,data:aPuYjsU=,iv:Y7kTvCAuDsdmlXuVJ1w31mLrFlwJLN+hiBIxBnm1GsU=,tag:9rQQx2BiduBdEy+hCCyJtA==,type:str]
    authelia_secondary_email: ENC[AES256_GCM,data:w3TFrt0bkV8sZ6oQHBUWVg==,iv:DlbpS/2Ntw0KcGtBnCxHftrgwD2BB3RoToHS1jYvvnA=,tag:/AO33B6kLieSRTkUmc3GFg==,type:str]
    authelia_secondary_password_hash: ENC[AES256_GCM,data:wfz6oTZDkblwEzlF/K2dKZpfwc7Vknao9ds/PSDJuQYRj6oa8YymG2bPWroDYC1w/KCWlsXLyRG1JJThcTfAzuUHIgyqARdgXSKvJP4KuajwDYgnniJG4U0mN2u4dEjrFw==,iv:ST6g5oFc7ug6beXZEPlkszCMnPWdOBw8NUcoe5Y4akQ=,tag:CC6YjphhfqLGSerMyg3xYA==,type:str]
    authelia_secondary_username: ENC[AES256_GCM,data:V8OU,iv:OhEQRwtgPxkIbShqBwDQwsXA5mHuQAaCO9IncXvqQI0=,tag:HoGOSQALjIeVFPmFGE10Qw==,type:str]
    authelia_duo_integration_key: ENC[AES256_GCM,data:wqmd20AY/tCIiSBNg2HSeS3R9zg=,iv:N/iAErOb12c+gXLBxTwGtmEdTEUUuviwuVF08NDyn24=,tag:4n2q6uUbIGfxTwE5eaXdVQ==,type:str]
    authelia_duo_secret_key: ENC[AES256_GCM,data:bUXSkkvUaniEpTga/H+5NYeGCMOGVNB+KevQI2FLyl/kJr+3be4MvQ==,iv:6q/zKOyVKoaSFxE87qWF3lRAfQ2TvxovEP0LRMv2avQ=,tag:9ypZ0dAIAp1tuqIy3+B4Vg==,type:str]
    authelia_duo_hostname: ENC[AES256_GCM,data:HA8le9svhIf+w1Vz4BJEabB9HZ89YDHZPxwaqQ==,iv:jmJDihaMQcsnFjYYlUg/JTPaoNd6IjDCAmfq9rrYW9k=,tag:UnCusnQX6QKmSpDkeFt+8g==,type:str]
    authelia_storage_encryption_key: ENC[AES256_GCM,data:oO6lyJOZQzTNQDTbyBcG6JqH3Exi+komr8Z0p+8IVXcCNdCIryodnz9XsYUArG4dg/THydht/n/hKh+n2rrD0OahC+/59DkpW6BURmuEjqz/MH+AJAXZL8MpFSUQwv6UAVTqkH6Nl1ktxjNQz3rtC/BK4Ed5KvbGHzEejsOdDLQ=,iv:gOykxrT1CQUvLVUK38txnp+Ro/xOoQvXnjNm432xWXE=,tag:u7pKBYRt5SUkVbfvglRUYQ==,type:str]
    ddns_cf_token: ENC[AES256_GCM,data:5dEYo9OZmpGFoQ/IYoPuRgGLMgx2Zrytou9AWFmZUIabIPX4gN7O9g==,iv:pMBjY16DtEyqEwP0xBRDrrQ+8ubZSYl6XKAjEGiGz8w=,tag:GFHBbZDAVxEDswK6WHqPIQ==,type:str]
    ddns_cf_zone_id: ENC[AES256_GCM,data:VEnwFjCfH1rpTObt9jcAEqXKN/BqvJjIOCJ8TwKee+c=,iv:e1VSuytFYJ/p3SSUxnezF5VCULj2qIusUIUAyegUsQw=,tag:FUXxxKxf6c8RDLI7QIJn3A==,type:str]
    phantombot_discord_token: ENC[AES256_GCM,data:jcy2c0AgtHTuqosCvYJOyHtdkEG6pJzBcDxxhC2GP4RRZarNACio6dS7Qam3GbXo9NNzC0wgMJwtNFE=,iv:cEA7RPPZ+/SDlR7mxTl8/MJ0s9pc0pOuUF3KM/ZeogQ=,tag:HHlGfsQuVz258KeYEoPrbA==,type:str]
    phantombot_web_password: ENC[AES256_GCM,data:QNhs8mcPOaqeuRI=,iv:k/52kMaRAIyDXRBBO174T4RwFRZbIh0CNs7FVh/jRWs=,tag:8wTteq0l9anqxLk5o2rW4A==,type:str]
    phantombot_web_username: ENC[AES256_GCM,data:PqNZ,iv:zogt4GbAbKWVx8NNtI6JhkJ0zXd/66/K2CeMsUKWbsk=,tag:EKEZkXoSwC5prEA4aUOfSA==,type:str]
    phantombot_channel: ENC[AES256_GCM,data:72CDPzqKKKei51qshGc=,iv:rn80L91mClTAW+7ruoztWdLK50pYSRQN5O7EywB1UGU=,tag:kqk8jeEMMnkEnSR1xkZqGw==,type:str]
    vaultwarden_admin_token: ENC[AES256_GCM,data:gKpVbQPvZlwmZ1vTN7I61laZSktv/1rVEBdHZuaNBjNwJ+CQHzTknsW9nmybQhg+GDuLS1xfJzsjOJdXDevfAw==,iv:TAOcWL9gfQZRkL8RKFCVCXvfH8ggoSY3EILUJz+5oyE=,tag:+XmRfDR2e1SA9gyLN7Ytng==,type:str]
    vaultwarden_yubico_client_id: ENC[AES256_GCM,data:1C2OWok=,iv:NeO1OxthIzKB5P+NoCkQc6hZJzv61zUCf3cuIIQsr/Y=,tag:EtCjKKLF1WHopJdF1pIIQg==,type:str]
    vaultwarden_yubico_secret_key: ENC[AES256_GCM,data:pY7Ofn2333cnA6eLihKl1jI8uSttBrNq2Eq2KQ==,iv:deFVRSnAN+3r4eDxPvckPjlcOY6AEUPmWbAT/FQm3AI=,tag:vTNXRC1fLNo0ao9+S1ECsQ==,type:str]
    vpn_surfshark_username: ENC[AES256_GCM,data:hHm6Mwr4aVTND7G8yCUvUHFr1lnGWsWu,iv:850iyvSeh3QZY6QQLn5gKntGODPNuIlJArellY5soqo=,tag:6Ea25YMUrQk4CHRhE7O7yA==,type:str]
    vpn_surfshark_password: ENC[AES256_GCM,data:1Pv9/2p32fKkd9Gc9qjZdNBncM5U0ohN,iv:Wurn4mMEjY2K23ukOJ/eNG/1kI/z8byt2zbE3kfW1+w=,tag:OApreNAz/cqEDIPjPezAuQ==,type:str]
    foundry_username: ENC[AES256_GCM,data:/ka1XROlZfl1U01Y0w==,iv:8PiJSBT2ly4/4ee5qRWxnRkv6/Ou2E/Ne6cPhtN9mms=,tag:HBnIYY1XztN5/oBm0BA7cw==,type:str]
    foundry_password: ENC[AES256_GCM,data:MZBx7VLy6oMW9x0fcyj4CcO4P5Zm+DtxPLAUgO2vYFY=,iv:d43HAqHyXbRgKwITjAltUmUWKTIBv1r0bxQQbHADwxU=,tag:XF5+0IlFUDfn5sTrXSqRTw==,type:str]
    foundry_admin_token: ENC[AES256_GCM,data:I/umK93C1DD3U12S2R+FZJvhuSMUl963546TdF+Zhzo=,iv:dj5KNAvIpHSaRXW/cBZvc5/ersq7u8TY4xbTEglIrkM=,tag:vDT+YXbQoZY1zdefHWx7iw==,type:str]
    flux_discord_webhook: ENC[AES256_GCM,data:3nWosHMKUD5SXXy/FoigOs70ODgZzy0gDRntCR3sUQWv1IumpdmNpFi2LX+3TceJ94U9l3SDgnZuB78hemurxrtVpa1lYYZ8CRv4ZaCaSrFl8m0lR87zIRvClaSE8am1P5livvC5e+1klvbxaY3dPyODcGkRw7gZ,iv:pG3bg/Y5O/tkdsgFbGFyXDVBsHFOh/VY2gbMZTRBpTY=,tag:VzFjV08SMAqvcqobJ+CPtA==,type:str]
    grafana_admin_password: ENC[AES256_GCM,data:nnC+PyY1Fbro89vxyDLDET622Tm5bynqA7jqUEb2nz4=,iv:SdL63OJLG+1dDRPElEiN0fMqoKnvUW5mOT3vj2AFdKM=,tag:GDaNfBRPmPppayTjHRrZXw==,type:str]
    alertmanager_discord_webhook: ENC[AES256_GCM,data:Zt0KEKbwFvEe/XY8PFnWEMAjeoT936iY6GR1Hen0fhR9y87XSBE/BfzAk+b1zEgoOpprdE0KtZypawn+rM+yruvPiRnYOxjv3VIzrYrv3gCuIgK42o0LWjpdSG5V/IzEtkRgKzJyUQlJKu1vC12NZiE1fIGQgu+0oZS7XBOn,iv:U6BVJL9HsUxGxelRKeoox+oihVQWhJDYZDEzuKIGroU=,tag:Q1Q+TL+wB9wj3RvlllCeJg==,type:str]
    mqtt_ip: ENC[AES256_GCM,data:WaiG4zYYl+Dl5MQ2XA==,iv:XhIkLNvNHKf9mtEtWUUjcSXagsdjfx758HjtBie12Vc=,tag:E8FvJlXKUoCpWqzkwcGlbA==,type:str]
    camera_password: ENC[AES256_GCM,data:falzd6VbzbhvLQ==,iv:YGHhtFLPTsJyMo+Sp22M4nybj0aq20OgAU9ETKXjjuQ=,tag:L5w3xssDen+XgL7LIkCgEw==,type:str]
    traefik_load_balancer_ip: ENC[AES256_GCM,data:9mbYrr/jb+N+v/tt7w==,iv:+Fpu2ObLSbfEkZZx5qjYwPfXZpKFsnxyMMG7IjISOZo=,tag:BxscNKNB32YT1lHUxDYK6g==,type:str]
    traefik_internal_load_balancer_ip: ENC[AES256_GCM,data:KofYuTOmUVT/Z2ZBZw==,iv:gm6LfNllPMyENUu8opjabJDXcD7WtWCENJJwnnFvs9U=,tag:ix8LDaFI9O0yp4lM4dckxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-17T03:52:03Z"
    mac: ENC[AES256_GCM,data:ogQG1hU3ttCYAJbO5KHslfmQui5Q/yvPgPy7d2LHSk42+YPB7z2WyiMXAXmfj86gnTmNRQtPt6plgEzjxj5EUIGHngNBG8t7RwHnY96OGaF1i5tyDKsCeUaemPJ6mki5/UzkKeekmyYsRZVoZ1KjUqaQ3jxbwDD8wrpHnjuuL2o=,iv:7nrmKRdbjkk8lui8AAxnrMAiWwo1Sbz0mpqCLVyhWJ4=,tag:qgem1zCxalzrjus7kBv3Lw==,type:str]
    pgp:
        - created_at: "2024-12-17T03:52:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQELA9dfDYZ4g97FAQf1HtG2KteNnuHqLsXaIu5aBeFjLq+P9gQRclAtAysvyIuM
            EF5zxb/cOoK2A5VXoVPvftsqrocKgQXO6vOksoP+3daT1JhPmpncw+wbm2FH84S3
            R5eAHfxWvi4OtP9V2VT7w96S9aG+sk2eYd9peJ+a6T0qJaEnOtfY11D7lmthV0ab
            OvwpyTwUsna+ehy7xJ7vkwWwvWoT4CdIDTPqJpNBVYvYecUiWcP5jfQlr6AHGGns
            xeYuKDopZ18R22Ep1Jxl6H1dmtvCgDzS2Ginwjh3Us5jSW4YwMPpfpJtZmIxIMIV
            diNCBUhJEjYSTh8lfaONvNq00k3j/3g3hRRxISTr0l4BlGAVco17IS21Wx7VrI9w
            XB5awYZuNGOnTnH6lvbpDHs1A9pT1clOBbiYOQxaYXzDuJ1ual+Zz3hg6HfH6pDo
            6QO+evnO69cYTVvsIdbHI3Q2rGkb+aze9VykTskQ
            =JhRl
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2024-12-17T03:52:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ//Xqny/PZkIS+Ux1p4Bdw3oIERz+FfkA0JiGp/ttiHRFQW
            xVTVkGmiLp00IIrdAi/5wUMsiHJnFtH1SlVpn7BymNKYrUGNhwXzqdtMLlUTSvG+
            xJej12xTkthsyFpbifDWJYtuhbeOOrXTe3ReA9j9o/Rl/tKrUOTdwwypKOBtOTou
            AHTh5jtMwpbCq+ali9m6UsM0Ovi0OZqNtlf3GrF0KEtkjOql3ALW4Q1L4pg+kYDw
            zBFfNSCLxok3JjcqZBjsFz9sy8QZ49acgsg9DbBw2Hxi48+8ciFRhE6baXjs1HS7
            PokzSY6xtGOtE9wC4Qa72KHoGzC0NOiGyTQ1dgWWFCPq4XiLl3xJGu+TWNuXeEal
            UNHfhrUvZuYzt1NgQ0ngFePqcDMoPciFTcpI04uhCOqbcB6zjYANLQP4aOlGy8DO
            +wN3I8to6C+cglynLADP3uXL4kQ6eqMAIo9BtLWQQgtTle+IGb/KxTjTuX29AbS7
            xtpodjZkXkUavvo1eatbEeraHsDwy+9LZgad57SloTFeSKPoO5FjYQeiwLjBxOCJ
            oByC/W6WtGjgAHIg4nSCgHxdYPysFLI617wRwx8vXWbC0TLjD0+cFpzhVDxeMnHD
            XQRx85s15hMzFE/TF4gorqv+CWe3W3xvpa5vWip4Y4Qv8FV/FvQ2mgnT+VWdf6DS
            XgFXHSQimpOQq4YuMz3g+mya06KfXUSBOCSg3hSHlEcbjDWqhucKZi2Wi8dTmdqK
            9FjzTLPR9EBXQDbnEsHr7qCscOKhLvkOIw71ojxIFquvN8iTzdU82Tc+o1zBD6A=
            =8/dN
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2024-12-17T03:52:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/+LgFsAUmwA8ZhilIvBOftlvB0TPEAq+bcrL1kVCs0I5fE
            Ck9+rF6GqkFoJl7XO1ewAieov1nuncibduiIaSucxAOeLUN0xtkMNnn0L1SElp2A
            ncHvkoi9UZ4oc8Ykd43Zu0HBr/BIutzDOmIEAzaU4GzudHhjYAssWcwMTfAU9fQv
            DKhkWBtq+jI5y+7CrkDlgwvlwpJjiXxfLGFtMWuvgdetO9rwx85QbHS8eajyBUvg
            YPJ1xWxxTMRylR3ici1A5FNTlSAa8d5cRhCMb3bOImqAlL8XKNAYVcJ3VyZZmfgi
            +BpX8b26pj12FGLRYGCvVSkzGOaIqgT2VZp4+g4TILkpu8dRgIc+0FkpW02BlnkY
            dhBF9yD9/IlMrIunS6Rda9pFozyQe8mc6mdu8ATtvIm+B9PiuLOlwjooFcuYxSz3
            AZJMpuD3cY3UQuS45/IjbFWMRFj/lE6aG02jg112U0KzwvM2vgoVE6I72N/fM4rI
            C+Vh09DBHCZirQsTz/paW2d7Luges9bjfDVjnxymWpU0ttfYo8xSGwYnBARtW45s
            JIsq61YCAZgGt7uTvE/i7QbNiIHSD3NXy5UNzXMRCTndepNtcy1y6w/WmJ9VFmVJ
            /oqogw53uMIwsx2zJ5ne+be27MQ+bdRevaGmLkjutLtBNUwGJPDMNb40UYh23PvS
            XgGKxr7GyJYdI2HMo+o48cxxbU2/NJjJrAH3b2wKuNP+fTM9YX/wCnBhMfapqpgE
            jbwBwVGQAQJsDXo16GfQkAJtu35q98yxYInnYxgQXEv1+LDUBbN50jo4eWknRzI=
            =v7L1
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
