configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

repoServer:
  # 1. Define an emptyDir volume which will hold the custom binaries
  #    and other volumes for importing the GPG key used for decryption
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: gnupg-home
      emptyDir: {}
    - name: sops-gpg
      secret:
        secretName: sops-gpg-argo

  # 2. Use an init container to download/copy custom binaries into the emptyDir
  initContainers:
    - name: download-tools
      image: alpine:3.8
      command: [sh, -c]

      # Don't forget to update this to whatever the stable release version is
      # Note the lack of the `v` prefix unlike the git tag
      env:
        - name: AVP_VERSION
          value: "1.16.1"
      args:
        - >-
          wget -O argocd-vault-plugin
          https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

    - name: import-gpg-key
      image: argoproj/argocd:v2.1.7
      command: ["gpg", "--import","/sops-gpg/sops.asc"]
      env:
        - name: GNUPGHOME
          value: /gnupg-home/.gnupg
      volumeMounts:
        - mountPath: /sops-gpg
          name: sops-gpg
        - mountPath: /gnupg-home
          name: gnupg-home

  # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/argocd-vault-plugin
      subPath: argocd-vault-plugin
    - mountPath: /home/argocd/.gnupg
      name: gnupg-home
      subPath: .gnupg

  extraEnv:
    - name: GNUPGHOME
      value: /home/argocd/.gnupg

  # 4. Register the config management plugin
  configs:
    cmp:
      create: true
      plugins:
        argocd-vault-plugin:
          generate:
            command: ["argocd-vault-plugin"]
            args: ["generate", "./"]
