configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: gnupg-home
      emptyDir: {}
    - name: sops-gpg
      secret:
        secretName: sops-gpg-argo

  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: 1.16.1
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

    - name: import-gpg-key
      image: argoproj/argocd:v2.1.7
      command: ["gpg", "--import","/sops-gpg/sops.asc"]
      env:
        - name: GNUPGHOME
          value: /gnupg-home/.gnupg
      volumeMounts:
        - mountPath: /sops-gpg
          name: sops-gpg
        - mountPath: /gnupg-home
          name: gnupg-home

  extraContainers:
    - name: avp
      command: [/var/run/argocd/argocd-cmp-server]
      image: registry.access.redhat.com/ubi8
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      env:
        - name: GNUPGHOME
          value: /home/argocd/.gnupg
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp

        # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin

        # Important: Mount tools into $PATH
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin

        # Mount imported gpg keys
        - mountPath: /home/argocd/.gnupg
          name: gnupg-home
          subPath: .gnupg

