version: "3.5"
services:
  server:
    image: tekxit
    volumes:
      - /homelab/tekxit:/server
    networks:
      - webnet
    ports:
      - 25565:25565
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple
networks:
  webnet:
    external: true
