---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.1003
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "readarr.${domain}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/k8s-shared/torrents/completed
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/Books
    podSecurityContext:
      fsGroup: 568
    env:
      TZ: America/Toronto
