apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:kcWCgmvuOBjRmUGPmNZ1KdrF71jzr5elN3f3Qy+E60lwR1ecVecwAQ==,iv:3SsrRQvsnP4sT220vSVgrbWzoitX0Ob6lgN5RuRghew=,tag:Qo0l/WIqG1f2Q7OA4gEzbQ==,type:str]
sops:
    lastmodified: "2021-10-12T19:06:50Z"
    mac: ENC[AES256_GCM,data:CTl0SniBjWZ79h4V/b6zvHHQiCbL9Mu+LXJFV0lMzzjFGOgd7APNNg8W8hQF+nsy6EcgxOz8YUa5lrnM3SQONfErVmz7Bh2SJjrNnnHJatBgjFeA/kyi4V1u/qFxoGRn3xA5hM0TN3Vdi2MTlH5IjwPhg2K0gptw0CMWK8OiTFg=,iv:QlVeaFvgUK269ACTADz+esBJxH7k1XdV9xnK05vcAuU=,tag:1NondMr0WeICAj1lLj8U3A==,type:str]
    pgp:
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/YCRw2vyZJXviGvO/e7+TQYHUHdToP6VqJM+TWtyxkT5J
            8/249uaAd+xf+doz+Vw088yuJt2UELfZw4Mzruzb/jITpDyAG8AYV4Zyjhkw2sj7
            MWGAI2BvviM9RT3zGm3vXS030TKbyHuptfL0avHp3nRjp2YXdm17+l4qNV1tCo8J
            Nhp4ymQvJx2qUPAHTfmZII+JltHnyObQ5jcDlLdPa3DjL8pJHrwDY28z8S1uEzzW
            OopbZRQAdRaJEIA7v6FXJ1Yg3pL34rKhtDNDkUrNrKWDf7206KO4b9U3TuDJyt4+
            00hqeYNFYq9WX689ghd8WIqkfpGRlF40goRuIu2WFtJeAWujUC8hg0SBIDLl/0Hy
            soGLgqnzku+dvVln0Fq131XE23yeVbbw6DLzJV5f/CxFWwugU8vRjPoW+hf31OsK
            VlfjvPdTBb3VCaFb9EWvujtewzpxilgyNxAytpHEKg==
            =HnvA
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ//XpFu55lfgeJ1bqEmTkKhLU7ZYSriN9DZ00Bly4U+Bj/a
            SOYcBcz4zFlzCvKjF9UFGIK8d00Tr99jGEbb0YaNAOg26L1ruO1DAVr8jpjdnbHL
            0jPL9AYWkOT1hbGfWMaurb+JnqECgYC7vskwimWXJ5/8KQedQtdtkdSoaU4iLKOC
            YL+Uf3oUDMS6U46cF4Sj2GCAnUZU1dOHUKx5hkASGOdowPXSeNe5KzxVWi0Hn7Ro
            XAc80X4dpnO/3Y0SzhhLsUUxfKrG9SD6YAECZrOhVa7tHQ1VMMGT0AJxDPMqd2mN
            ZPPkHe9j/HQZxL9DbBGemEKzb2L8euIVtWHxRClLvLx7mg58tsh+NkBI0sYMYqi1
            L8Nciy3w9uH7LM7vs/kR2Ej0qrGCWgYfTZzvwthwJ0PKOrY8g8YAro24XImUvls2
            GOVaU38UAy54nrdj7tMfqtWwqjG3PYwsMdBdyMsEdw/umD75I1XG0aKrUF+IAav0
            pGn5M2u/1NeyJhdcJM4w7zCmR2ISSWOEckfNo6Fpef2qPqDbdxUE3ZvrZN4n7bG/
            lYyPGzgb2ZJlRPfK1j17nd7s9C75nBhS9kY8n/F4DqctCF2N7bXge6xmfNkdF6pT
            6fOQMcw5ucn2OW0EEbQEZ2vUxcXVIiSIMmHQxOhEg0YWKxZwL2xYXzdceuJitrrS
            XgGjwF9H7AazRjpqMBD5HgDMCoNZTg5m96WkO85bKcio7tiGtO+49jwg5PHDCYHo
            FddEb0nk3uvEYJZj+nFeKPQN5PqgbAW+siBUzpUuVleFeYL+gnYj1/g7Hx92AOU=
            =an7f
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ//bJQMrspzgy9G0acVzJOYf5z6ySPzXGTPKmaHQ+b7zGa1
            qmzpVnMSgbel+kmT03NVAnLC6pEZ6RkYVPhdLt31Sr78Jdp8qBl03aj8ZkuermcK
            IrsCqm8W12RSvOrTtu1DfqKEdSvS5BFLuy/fMuwomEfHAHDLQIbWBYRM657G+L4c
            Wsa0EGXFeSwbKsMdM5pwOqk+bK7rj1HY3We2Sa2/9qEmhDRXfjeJhuP6sjgoI2y6
            YINSgOIRMUwcqa0WBimOvN2AgcFv92WNhqz8PvxZ5nQ420I/uSRDqAt8oEvmaNV1
            yb6wPEdSmGW112Pn6aoXA5UlA3aWl8WaYVh0R2AK2ZNqX02eMay9iL6+9SFVs0QE
            vhIksVCSaPAZbnb6HcCmf4K9gkBBanLMiyd1IlG4LTjdVyGBsRgoEt3JplHbIg5f
            jH4c3ZnCEKCd+Zt/sB18zDaQC4M30TP+bVg4KmznUkGJJVMU5bQEb8NYjfDS4pie
            MjxXSiRuuznBFgH4DU7NuPfCc6w3YW4CglsIhmeqVFtnWkBhaW/3M8xbYuuRwHgc
            BkVEOMkrnF+VBakw4E3jCtd2uHgstdy/4yKLBtQ4LLODkZEU+qwNqEa2z6ekaJnZ
            A0+f0rM6uygDAbNqSKyGtxMIc5tRZqWO50kkFgBuxSc/ROwCGh/WWaBgepUdTqLS
            XgHcWyqOtY9IAhnsRLUMHiB1TNQdx776gUAqvchzOpJPOGqfn+OcVMUbHF/XBvv4
            3kICGvK7faG2xlRZgf7M9AVeCajTpm+2JsGvkYVRLlqnm0BrH9jpQqpppdAqOQs=
            =5QSG
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdAYd3sCPAPF6FC2DwTG++29vo/WEciXybKZWz6djDt2SYw
            BZlLReSS8iDlBceM+0YpDzmj6qs+faqtK6pJbbZhSnBDJi4PALrKViG0lVx0k3Tg
            0l4B79LIX7f1+DB8gv+eRGaJTgR0yIzWmAiSjrwynO7E4eG8+CUkwjnh4MiucxIK
            H9QQjlNYmm/QDuKj5cyHH5X+LJ5YnP5fw+XvpvOqDSt38ApwLb+z/uPy97sZz/y2
            =o09r
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DrvgYWgvgiW4SAQdAbzPhvlY2Y4Vx+lcppFJRc+fGYFas5vq+xDzaWmaZA00w
            GhqsKrz9C06QOlvnWbiG8Ckg/7GB6fj3tkrPQ8WcRRT/T25d1JAYpq7XWdWYU24a
            0l4ByyJPgG+NLCv85o7zZqxU74HxtyLbXyI9vtszJP8uX4Cp0wwPg53ki2NnLwS9
            IaB1BlSu6qTSCGBrxkp8HgCfHl7xMIyznakF7b7tifQC/nQL1/ax90aM3QSFH1zG
            =hyG3
            -----END PGP MESSAGE-----
          fp: F75CA0B534439722B612D343FAB6BD4E290CA406
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
