---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js
  namespace: home
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: zwavejs/zwave-js-ui
      tag: 9.31.0
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "zwave.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000
    persistence:
      config:
        enabled: true
        existingClaim: zwave-js-config
        mountPath: /usr/src/app/store
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
        mountPath: /dev/zwave
        hostPathType: CharDevice

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - docker02

    podSecurityContext:
      fsGroup: 568
    securityContext:
      privileged: true
    env:
      TZ: America/Toronto
