---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: unifi
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.2.95
    hostNetwork: true
    # ingress:
    #   main:
    #     enabled: true
    #     hosts:
    #       - host: "unifi.${domain}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
    podSecurityContext:
      fsGroup: 568
    env:
      TZ: America/Toronto
