---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
