---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.32.6
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "bw.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    podSecurityContext:
      fsGroup: 568
    env:
      DATA_FOLDER: "config"
      TZ: America/Toronto
      YUBICO_CLIENT_ID: "${vaultwarden_yubico_client_id}"
      YUBICO_SECRET_KEY: "${vaultwarden_yubico_secret_key}"
      ADMIN_TOKEN: "${vaultwarden_admin_token}"
