---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: vaultwarden
      version: 4.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.24.0
    ingress:
      main:
        enabled: true
        hosts:
          - host: "bw.${domain}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    podSecurityContext:
      fsGroup: 568
    env:
      TZ: America/Toronto
      YUBICO_CLIENT_ID: "${vaultwarden_yubico_client_id}"
      YUBICO_SECRET_KEY: "${vaultwarden_yubico_secret_key}"
      ADMIN_TOKEN: "${vaultwarden_admin_token}"
