---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: vaultwarden/server
              tag: 1.34.1
            env:
              DATA_FOLDER: "config"
              TZ: America/Toronto
              YUBICO_CLIENT_ID: "${vaultwarden_yubico_client_id}"
              YUBICO_SECRET_KEY: "${vaultwarden_yubico_secret_key}"
              ADMIN_TOKEN: "${vaultwarden_admin_token}"
              EXPERIMENTAL_CLIENT_FEATURE_FLAGS: "ssh-key-vault-item,ssh-agent"

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "bw.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012

    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
