apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-encryption-key
    namespace: admin
stringData:
    encryption_key: ENC[AES256_GCM,data:uUaCVvl2ONgVJnjunC4XveyVtmkSgkl8SPd9Q4maWto/KOQiTmQPN45QjeE=,iv:Pudyc9HBQKLNByy9QDl42kmcauogvAHQB4LSf0R1LGQ=,tag:F/OkxDkLeUyGPKTHuunyIA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T18:14:30Z"
    mac: ENC[AES256_GCM,data:neHGtcbKhsCfIMvLl00PqRkScb0UBURmHPEtfV4sCHhQ4GJ87Yod7M2q+CklhRELUCZIdqX7dI4KQMuO0eK0CL0xFaN1HOiHKlzdSKXrMbxMsitfB3WwSSsbkSr05rsjQUoTl++95ZUO0/QmpRzsUSQ+OIxFal5wphI+X2RKDoc=,iv:HsuPLraKBM79CcVEoyE5IwOlKu/o1fR0+g4KFqf6H4A=,tag:Zx4Mi1mPs/AdXcBmbanaDw==,type:str]
    pgp:
        - created_at: "2026-07-23T18:14:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/TwWNI8q/ZwgOHHrUXfR1q9IHnlLtHr4tRj1DkvHMsDTJ
            LaotHC3zJTHF3ms/poVY8u55U+lYVXYVPZylKvDnwiEYwsaRZ4SiYRxYeQBSV90t
            8JJ2bT+CcG5yaUP9Fma5rWbK/LCJBwkdiyt+ADWjMZ6JsBTDKfzfBek4WKTYt8PX
            sbVDHj8HilwYH+VdqNGjoS9hDZ/2zOo/kI9Mt2tHxukIGGukiew3cMI6DkLij0/U
            Cc5zlQmPbb3xDI9eHZ6aV+eqLzzCGBM8ZO0d3SnXln3szwPpcC7B83WG5GHhl7yU
            UUOwDRNqjU8AVoKkw1Mv4V+MW9a7rQaFyojiBH4QH9JeAY/jDMZEX+c3v3h243oS
            cbv2SESkaJyW0fN8uW/9Kfhz4+DaXKAWTqxUjw/yZ33MmnToNRO28GiK8vW0P4Bd
            ICCakgQuRf3KNGseSXNAeDF4ypz1DnkvxGvZCroGIQ==
            =8hhM
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2026-07-23T18:14:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0AQ//SIWHlIq6NwFuVimAqDWP2X7IDdLbrrslZ4lt03f3kQJH
            8m3C6ti4qWPckl6j3jul3l2NsQnJWeJmpswPDqJDsCRyu05cbioL/TK5zeC7Dxti
            IQPlwUPgpeWrby8hQySYf/v98bzow7sb/hTPMyOk+Xqj49T/kxU1f0XlnlumyKcZ
            SHypIjMpKNMgIyMDmvwVhzzahQXHvTGStvKk+5C19W+7C8rc3FaksQWpCC0PM8oc
            yenJdAWOG3gIpfKoxaJ0rk/fY2bwZfiLTQKvzpZsI0zsjDkM0+hjviCYj/MV5F9S
            cAj+dWxmIBBWCUdnyJFdVmHal6IHc5zcanmR0ZQ9f50YnTuuF/r5x+S/q2yRbebE
            cnRafcJaYUjIK/leLMDZGucCe7CpkJziuSyjZ5ZAWL5wr5fLiXYVWWNdMAavzf9w
            wRj6se/PwdpC4PttNctwk4dj9VqPxFo851fF9uBaw0W+8+wCMPjic/AKbQDyxTNF
            kXLSCqVeovodMWCmOpNPmdvmrvdD221+xuggOUXyvOLFVVLPdYmw8hDBb/DwEP6M
            OB31B1SdTunAVsHK2nmOUXVVL4P4Fw89CP8mAAs2XmAm+9nID2ncX+QHvfarHZgc
            jxoVbRU+DsfLMf0pjdgXl9PXCHOkISpRsFcpMFPGHwb8kpYf74XO9/wTiqwoIyPS
            XgGhBbf1fFqVY94ATR17shAsrTNAUunGbsn9YFIpR8kKg1UQrIDFGrA7TIoGtYpC
            +ua61ikKRLbstVUthXyf8X2tBR2WJoBHRpIgMMrwkvtlzZcOtT4OvOwu1KZKfr0=
            =PTei
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2026-07-23T18:14:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8ARAAi3bzKNW+Q933eK5lPdmhZ2NTzcfunvMknQWu6vCxhQxT
            3pUnXeUkoWaOu9T0oJZSC8l6KbxMA7KSg98yveyRDz+n/dQ/o3Lo+dgZZWMkus1l
            0Avg/+CqvvzABJEm+etKOMF33ancaw3OUKjksYSPr6w0loxXhU77wp35Ei5i6J4f
            EItrQqjAhT9rr/fuH3WT/gw5BoYtC3Eh2wXfvFPRKocFgGY75o5u+xQaDUUomrv+
            d2K6ejRWUk++idpkC3b/sutMiGH85oHgxHgYaqmULDnDbafqzmyeqBPVlkZVmAGh
            R+NDFq3+VoQbS2qCSb6w4MDz/T1eJryGoIa71djZeuS1h5OqfcumjUobS5NKDAZT
            +TGWkwIlSpvBi6C5ygpQZ2rxe8ClsCF7Dee/GOZRwdCY8X1q+eXKTQFkDTvYd2Jn
            wROX/4j7cPqxxkk2H+iV6EzVbvbn6MkM8X4JsaXxNUcwZSBX9cOIZactVwzOW1mf
            4mMfCCqRK8zpl1B11HpbZR6Dgi0tIjyWLFHJwnB5Va2BGwNJqS5PbqxDNLXEkzHO
            H7nSH3Fl27R/gJkewR9HmS1S8dAzZBmC95yL7TfAgF/OsWCphnHiQmXy/ngM7qeX
            bznweOEzSPLc/0P+58qlzfjOx9oNNmKSls8jB/npmtHgramO19gHzw4crmhWfrjS
            XgFvJUxAfxHBzJbwHRZsf5VRH8wvxCYXlSwiPveGOw6eV8OaQ/YR+PrUszgVm4e3
            6NoUZsFOkhalF4kTHDstnETuSzfpnpRMNKwXjq9NO5LK5TUOEBvoA5XsCo3YlKs=
            =XhBr
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2026-07-23T18:14:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdA2GlwIEYY/MvV22EgAgpd3jU1XhIovKcZbKN4Pe+m+V0w
            swNHj2gIRIkaXLiMOBkppIl4M5wdILbrt9n7dVa4CpbEWIFu9kq6J9t+nlm05ZEl
            0l4BitwHGeJp55x6MhsGF0jzeilMO1bXHRaIgwVeaQtYuDxbJWMPguGjBeo47fdM
            bk9MyMj25yGi5yErqZilyQC45UzXmQYDpD8Z0g0ZNuCloeL1MRLodD5px3PhCbVG
            =7tX9
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
        - created_at: "2026-07-23T18:14:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DrvgYWgvgiW4SAQdAVJQOkLH6Y1ff+/pkS3oB5Jnd0JIY3qxCP/MapdWwrXYw
            SBFeqqVkcPkqM1i+t3MWUOuhDzeQh7akUKTl0ySrT33MndUAgT5R6j4ZJsEcx84q
            0l4BlOv0F9V/hgSd7+aKoyOkEwfcP+hkNUMiOhNrLisRlv/b6YyNcRYwepEoqMAo
            1u15QoF3ssIMy3FGH9FmuNzhBj2i4hDwpOlMB5sVX7rgpwqbPIy7BNKrW3i3ApAa
            =6FxH
            -----END PGP MESSAGE-----
          fp: F75CA0B534439722B612D343FAB6BD4E290CA406
    version: 3.13.1
