---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.11
    ingress:
      main:
        enabled: true
        hosts:
          - host: "jellyfin.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 8096
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      transcode:
        enabled: true
        type: emptyDir
        mountPath: /config/transcodes
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/
        mountPath: /media
    podSecurityContext:
      fsGroup: 568
    env:
      TZ: America/Toronto
