---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-configmap
  namespace: admin
data:
  config.yaml: |
    storage:
      type: sqlite
      caching: true
      path: /config/gatus.db

    alerting:
      discord:
        webhook-url: "${gatus_discord_webhook}"

    connectivity:
      checker:
        target: 1.1.1.1:53
        interval: 1m

    endpoints:
      - name: kube-vip-dns-record
        url: "192.168.0.1"
        dns:
          query-name: "${domain}"
          query-type: "A"
        conditions:
          - "[BODY] == ${traefik_load_balancer_ip}"
          - "[DNS_RCODE] == NOERROR"
