---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: admin
  labels:
    recurring-job-group.longhorn.io/daily: enabled
    recurring-job.longhorn.io/source: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
