---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - rbac.yaml
  - data-pvc.yaml
configMapGenerator:
  - name: gatus-configmap
    files:
      - config.yaml=./config.yaml
