environments:
  default:
    values:
    - domain: "radarr.{{ .Values.shared.domain }}"
    - middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"

---

releases:
- name: radarr
  namespace: media
  chart: k8s-at-home/radarr
  values:
  - ../../ingress.yaml.gotmpl
  - persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /homelab/radarr
        mountPath: /config
      media:
        enabled: true
        type: hostPath
        hostPath: /storage/Movies
        mountPath: /movies
      downloads:
        enabled: true
        type: hostPath
        hostPath: /homelab/transmission/completed
        mountPath: /downloads
  - env:
      TZ: America/Toronto
