environments:
  default:
    values:
    - domain: "transmission.{{ .Values.shared.domain }}"
    - middlewares: "localOnly@file,admin-forwardauth-authelia@kubernetescrd"

---

releases:
- name: transmission
  namespace: media
  chart: ../../k8s-at-home-template
  values:
  - ../../ingress.yaml.gotmpl
  - image:
      repository: haugene/transmission-openvpn
  - service:
      main:
        ports:
          http:
            port: 9091
  - persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /homelab/transmission
        mountPath: /data
  - env:
      OPENVPN_PROVIDER: SURFSHARK
      OPENVPN_USERNAME: "{{ .Values.vpn.surfshark_username }}"
      OPENVPN_PASSWORD: "{{ .Values.vpn.surfshark_password }}"
      OPENVPN_CONFIG: nl-ams_udp
      LOCAL_NETWORK: "10.43.0.0/16"
  - securityContext:
      capabilities:
        add:
        - NET_ADMIN
