version: "3.5"
services:
  controller:
    image: linuxserver/unifi-controller
    networks:
      - webnet
    volumes:
      - /homelab/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    deploy:
      placement:
        constraints:
          - node.hostname == shirleytemple

networks:
  webnet:
    external: true
