---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundry
  namespace: misc
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        pod:
          # Without the explicit hostname foundry will ask for the licence agreement every time
          hostname: foundry-container
        containers:
          main:
            image:
              repository: felddy/foundryvtt
              tag: "13.350"
            env:
              CONTAINER_CACHE: /data/container_cache
              FOUNDRY_ADMIN_KEY: ${foundry_admin_token}
              FOUNDRY_WORLD: twbtw
              FOUNDRY_VERSION: 10.291
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "foundry.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 30000

    persistence:
      data:
        enabled: true
        existingClaim: foundry-config
