version: "3.5"
services:
  authelia:
    image: authelia/authelia
    volumes:
      - /homelab/authelia:/config
    networks:
      - webnet
    deploy:
      labels:
        - traefik.http.routers.authelia.rule=Host(`login.${domain}`)
        - traefik.http.routers.authelia.tls=true
        - traefik.http.services.authelia-service.loadbalancer.server.port=9091
        - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${domain}/'
        - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
        - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'
      placement:
        constraints:
          - node.hostname == shirleytemple

  keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    volumes:
      - /homelab/keycloak/realm-config:/opt/jboss/keycloak/realm-config
      - /homelab/keycloak/database:/opt/jboss/keycloak/standalone/data
    networks:
      - webnet
    environment:
      - PROXY_ADDRESS_FORWARDING=true
    deploy:
      labels:
        - traefik.http.routers.keycloak.rule=Host(`keycloak.${domain}`)
        - traefik.http.routers.keycloak.tls=true
        - traefik.http.services.keycloak-service.loadbalancer.server.port=8080
      placement:
        constraints:
          - node.hostname == shirleytemple

networks:
  webnet:
    external: true
