---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghost
              tag: 5.129.0-alpine
            env:
              TZ: America/Toronto
              NODE_ENV: development
              database__connection__filename: /var/lib/ghost/content/data/ghost.db

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "ghost.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
    service:
      main:
        controller: main
        ports:
          http:
            port: 2368

    persistence:
      config:
        enabled: true
        existingClaim: ghost-data
        globalMounts:
          - path: /var/lib/ghost/content
            readOnly: false
