---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: monitoring
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.55.3
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 5m
  values:
    serviceMonitor:
      enabled: true
