environments:
  default:
    values:
    - domain: "foundry.{{ .Values.shared.domain }}"

---

releases:
- name: foundry
  namespace: dnd
  chart: ../../k8s-at-home-template
  values:
    - ../../ingress.yaml.gotmpl
    - image:
        repository: felddy/foundryvtt
    - service:
        main:
          ports:
            http:
              port: 30000
    - persistence:
        data:
          enabled: true
          type: hostPath
          hostPath: /homelab/foundry
          mountPath: /data
    - env:
        PHANTOMBOT_USER: "{{ .Values.phantombot.channel }}bot"
        PHANTOMBOT_CHANNEL: "{{ .Values.phantombot.channel }}"
        PHANTOMBOT_USEHTTPS: "false"
        FOUNDRY_PASSWORD: "{{ .Values.foundry.password }}"
        FOUNDRY_USERNAME: "{{ .Values.foundry.username }}"
        FOUNDRY_ADMIN_KEY: "{{ .Values.foundry.admin_token }}"
