---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-config
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
