---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dashy
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/lissy93/dashy
      tag: 2.1.0
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "dashy.${domain}"
            paths:
              - path: /
                pathType: Prefix

    service:
      main:
        ports:
          http:
            port: 80

    persistence:
      config:
        enabled: true
        mountPath: /app/public
        existingClaim: dashy-config
    podSecurityContext:
      fsGroup: 568
