---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: utils
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/lissy93/dashy
              tag: 3.1.0

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "admin-forwardauth-authelia@kubernetescrd"
        hosts:
          - host: "dashy.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        existingClaim: dashy-config
        globalMounts:
          - path: /app/user-data
            readOnly: false
