apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
spec:
  project: default
  source:
    repoURL: https://github.com/WolfeCub/home-ops
    targetRevision: argo
    path: ./argo/testing/
    plugin:
      name: replacer-kustomize
      env:
          - name: SOPS_FILE
            value: ./secret.sops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: blah
