environments:
  default:
    values:
    - domain: "{{ .Values.shared.domain }}"

---

releases:
- name: hugo
  namespace: blog
  chart: ../../k8s-at-home-template
  values:
    - ../../ingress.yaml.gotmpl
    - image:
        repository: ghcr.io/wolfecub/blog
    - service:
        main:
          ports:
            http:
              port: 80
