---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: admin
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: authelia
      version: 0.10.47
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      interval: 5m
  valueFiles:
    - ./values.yaml
