apiVersion: v1
data:
    private.pem: ENC[AES256_GCM,data:yHsF+6QXo4FsBMWFAQAyh6SchlF5l02GOsz/lFFo1klewIHM3+ZTPx/Zw2n22dV4DcGLa4ckgwgcGa2im/97gIYGIwWXYJehruTg1XJ9BVlh2nNbe5kPtZ7vKg84NtF6r9mN7n9o4KOfwJ0ljKKXT/slsQX1VZFLUGrP0fAgzZM6+Or7MhvjRwbUV7e7WNLIY6AD7NDdaohFzG5FUZX3pis+ti2L2t0BPsh39eeg8kwkprZE1FNvZAVO5yQA72oUGH+2ligBqZA1sBB1VDzgZJpejLNXvwCzW2tcUDcnJ7honkBF08kXYhapd+NbQBzARiik+QoReaGzgucOXtZVxWVz1lI8+mGTnjqfItZLZE8fZavDo8uQNHoZjIpLf0HKTJyjdgkCtAOsoDkL643AnTXsG14bTNry7NCvjiu1E/yE/Fh+av2ESET24bKdI6ULbEhY9kK7+IXnkj2FVifBswaPiRIaQbzGNWwDH89swzMYlUWrJh0+bFJ3Ueg5Ar4QBDe5KPlBtpWzAHvTZzp+6EeeRVL2vV3ao8mjeSK4eMC5lo3uvRF8Zik+LuGn5X4gur1mKTDw7u+sPFIjccdGmYNY/fvYK344YPAiRgIE9/BRYTgzZd8fplb6F9cbT0AXW1AiqD3OPdsHC4GqojHIfyMVA6T6OETNWs2XiFnhorad6p2jj2M9H+m00c88xnWTTO0e0GiiNyiyHPKgA5qDmF2zUqhw5KygQCrsrL3dWdoSwwovLxoGc986F0eS6ZnfBONMBn7WGu/TUFqYksB/KD6ZP9KNu4jC5asr2dAZ7WhiguPkxaFdGaMZH5UVQEBJ5QgVVaYRGAnFTBR0nUn4scqPXX7/ztrRNV7bSO24eJXy7sNB/rnhh1SdigO0mGLNa3bxWUJ0IW8jTKPfSQhZoqqfO7PBlN3evngb9tQmg1px1VOEU7fixfOOditIgN2tz5uVW4LYjMDVtdAcPsmftJOduXSnBPkCG1GGgeBsADO9m0uC0JOJyXR0PHRwW6yb6pWzIAAf24GQwBQnehZKPI6EHHOHSrgwLN5fMxQN3CPn+7CGxlKoJ+rm53ys5zsmV2rIGI99x8dEotUUsCeB5t9OXQ+jcZLAPuatau+IWQKoYy4k+9M9ISPe/aKFVE6uG1bMULI8gkEhm1V5OSHtDRAyjM5zsgvkzxucy9T9MpM2C1qC79uHFTjIDHb7EDcNFWWamt6LDP+PyamFIx1DV24BL9npb8hTxACBFIlFaw29O1yuCpIQV7c4t3+Y2q52MtUaW3kMJOPXp14kO6JHlfKL3zS3O9uVQ3c/KimoUv3GyU+PX9aKn/XZDnOllFDCDCq4eJQehzKrO7tcwiML3wdW218sFcwAIugsIILRt0peJdredjktDAFyUJvi4k4NIXHAWpc5eQUUWT2pclRt0r8jxLsK2UJAFX707x/meLcZJilfdGj17q4tZ/yu3+vaViMg3AYpE/g4vgX7Q8OU3cqyXDOLEk/cO5slkLb+LI1+gcPdYIjNdbhzn9/KHixItz6RhhZrrCdoKm27X4TIteG/GxtH2cCQXEK+6IjaltqgDcICn/kwwdfIqOr8V5vtXaEIRwp8eeArIA43N0gcB6bJRFfUQ1NRNjb8Dr8Be7gxrhc1aiULBy3Wwm9nOl2MJs8a27GNXUk6PHWW0VRMcEdOhuOOJYNn8G/qiNP0Ijwt22Jk4WPfCenXGM30KzhOGsKByiZ9U+rzrtZnCV6k6EDpd67aHSqJFvZtlM7Lw+0/5CcTfYVyIRCgKfX8SrcUahgZU6GZbB37rUC02ZQyYnqggPKoJnnG9pzFhKJtARZkC7BAllFjMNW+f01eN565WisMUMENusBVUpmqhnPqQHPB7GgYzEeLAOBywBQaAqBV7k9i1EXSsocf3S7EDVkHtjIAbNTQt0ri/WyTv1CchQqTIk01MXlTendDbpzWdNPSPmkxepFVIOwUQh2WEzzalv9ems3ayO28Tu/SqKa7D+yGyGJyuGwjburzBTwoXXfu9k+GfjMJpI5VkQeR7z2gb2cPzukCiKRM2P60qxQlbyhu3PHH8XXNMuCJDjtGfniUguoFmsBPGNLWv/d0bs2E6Ho8xG9cpDG1fn+fB5BezC7L5Sl/Q8tEbIBwv/BYeGDa9Fn7PX63Y9tsjs0U3pxeOHuUpZ8z/f/hSB3dNFRZ1JU4nbVT8K6Vxj3mheOpCBXyl0b5DDrnv7WvACzCN4YXxgB0ixRk/eoHD3AOe7K/mx7330qG9d9sA5zQBn0goRFuAwQ9CQmATzyF2zuwGLgSa1d3aSSwZ2gxv+HtbFMm45Cx9yQWoe2ozWtD6CQCePmB5OHwmb06vmXarmhU/4NN9el/UuP1MOQ1IAqou96MgiU+5EsZvw6ug+9NuYhICbEUMT/MGoN2ltfxGdjq5aMxqiU/aRRnW2Xl7ZL7liMFPdaCZh6e0IoAfgbKwwAaA/SKItgU01hS7dTHvLAD8JDSskS8DIN3GqZ3jfzs0d3uy3iNeIkmhM3RWDR668U5Br3Jmm2veFFgjDlhXOer1vOxJMFtQicLEbbrfZoAvY4c4WZHYxU8i1XokJ6e67EZGFfjus7z4jYCvOCJ0ifbuV72jWx3AcFj3Xlznz/QyP6lbEdFt5ENVnpVg5/xvlu6PsfRek7wGfnVYd8THhW5wH5vWYZ4sdY6pDOoandtSN2IbOr81FC/a6dndq7IGz7pk5V43pW463EVWMhikACyJN9hDe1r1r4ue5kL4RP65XjtTzw/5IOUwTaJwRhCCcByt2ruG+Bg0HBpV/VAjf0xb4wMEfJ4iVmB2dREggHbT07KVbq4djIu5N+4jFN9rUsg/lzrFIVPSO2QL1WaIp/43dbrk8eO8D40vHkfw49hI97qy5d2U0gxrUV/tiFV9QPn51GEzTpN+jefn94lwDv4fKf7Xl4rG4oDFYxjrTdWypklXpjEZ5yf4QpP1T7nv1ndg0yXWB4YBfgVOjnVB3cwlXN147Fu4BCu9dhMNePcz19ghA==,iv:jZtvIDPBWzHYo49VWXiJbBi+seQkh3YbOyc2olCV2RY=,tag:s7OfJtnJmvDR4k0BwzmXag==,type:str]
kind: Secret
metadata:
    name: oidc-jwk
    namespace: admin
sops:
    lastmodified: "2025-10-23T16:32:16Z"
    mac: ENC[AES256_GCM,data:WjnwmkjDHZ/FIUklM44VqHrK1ZkUMdJWD5MCAigkOtK/vOiSRmdZLi9wi5r3ws1m+1KSq4iwit4GjTKSeBqlEtpmw3MW46KtoUs9agi8cmsDE88iP3BpB9sJpGhtAPZzrJwuDRMRJ5cRREM9wPkyQbpf/UcFC1eVakSUBUaAkqs=,iv:BHZncShcfSuLcmStxhyTdNIRSvR0rgvCy83q3rOFjkU=,tag:espc/ndsCQhJ0WeV66mYAA==,type:str]
    pgp:
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA9dfDYZ4g97FAQf/SQRTn1cX1gLZ4GMXA3IMMU4NTooW5meI6VpyzyHnp5kV
            x2cPPXWiD7rx2xwyXK5G6NN8+jizrAwSKjHkRq31hXw+ztqkAhzdnXtVo1Hy+Ko5
            +vmxCPIfnFRJH8DZ5tAAL3fiptFlzfxrFNnijlsFPLzkbss5YWdnQYPNvCamWXut
            oxXiVAeKONJpxjwQy0e4HnkfJDGeQdi7cHop0/vhXlauxxflIQ6rKwIso802247R
            Nw7IoKaednm6n+fBDOA6pdd6by5VkMu3U45OkoYO0wkRwshthwdNidQmKV6CVGbG
            ozmzeP+Hm4DvyOw+D8wNgcUTLyAEkh+ZfzqT6nkmO9JeASIygYHQPnTY0ZaJW/aQ
            QZaMGaOogW6qD+rhfJ8r1SZxqF8QlW+rqgP0O1Q6bzFhCczDdev0mnY7UZBuHZ/e
            oTELr7o58syjCJ4ZuCRir1fEyxWv2NlNPHKqFskLRA==
            =zxf2
            -----END PGP MESSAGE-----
          fp: 664E540B1D1D5CBED091439D18942A942DE01A34
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5RW6wuzd0D0ARAAlqnkB2ZGFrlr/7buyn42XoI8iLF1j3qF5UpxfVpT23Wy
            BLJOzcBymRzJzO9pv0dq7Vw5wo2Mxxry0wD+b6LD0owbtNFRs/lIuENNDK9/MXqO
            rbhmpLwz+uJIxvI5ezRXRNkV74kjQxrf6BLpNs4rtFkiju1HaEBosUxxMMVvB3mN
            +7/3QATOZl0Ob3T37zNeeVGfDwxfNerAzOytB+rNPsYOfLRASF61g4cFxHdp3eEV
            mfrj/IgZ2ePplgSgyRU8TMss1BUj8uxwGRhNAQbgxZxbI9N2qPsG2OP//rrEQ1+P
            SVk7lsTQN0C1ZVpT+Iw/BEwGODlgDLCKQVBGvMpDls/uNjxr3sMpH32XZY32iwNb
            /YTkW0eeXrJiT0Yyh/2VLGd8SK+aYDBOXVa8cBUAjwusn5Sh3c3jHowcbtCuocKm
            ZY9AqVtyqUbtsRKDQEzYz+1W0nUDKOOMkWYRv5KlagRw+qHJOmcFCrrK9Oly3bPF
            BhC9FhZQDXvYeqI6vMTBbUtdD7Vb0Oa4J/+BvsPaqEPcLqk1sKhrJulHF+bMLEgY
            oNSAP7ueOxkruXbHaTMFTL3JsqdnRBwV5nV/lGoqcya507xTuFG+nmPPs1nzLJqN
            SOie6Km0o64FAqgd26AVZM7+YZagcbbkgxc/i894rfACRnw149Of97eReF+jwLvS
            XgFZ4TqRzzfWEmJgSjWAXkMT04r2l0l0xtG+s5HKrWE9chqXbNbKOBqPxAT2z0Fu
            9inKLOY4n9zQpeyOiZ3YnNMvPpu764ec0UqQeFhA45rX1UnEYKoNA9ntInmO9hc=
            =OMPs
            -----END PGP MESSAGE-----
          fp: 17948F5E4A7A77C68DECD1A507AE158F0D50CD68
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FJYEpSIDU8AQ/+NPG01fNg+F1DuQ2IRm8ROM0gOXQ/HAXbluQQLvFluYWc
            37VvQ57DH03kgFxpfhTyXagFTxMhq47vceFZvc9iQ9CejH17Ii4G/ufEXyhw7rfR
            ZunzXaAEhKGqGeFkaTNinNLEF3P5if0j+B25hwzJkgGArzW52y4rJeRYeXGSjr70
            TbyktL4cG7nEGY4YARUGziuStwO7f2LmLEGbR3cP86RFt4mW/+Lq2vRQ0WHh98PU
            qgWNNI9qKJdmJxcW8QJU2AQLohAgcx/YLh6eSPVVWOIqAsJxdAVxdGKloUCxRHR5
            55P/LK0+wolGVOA1QHNT+JTT/HOPP8VCGmf1TqyOzycu4vuh/ZdVLqRhK3VHfT7+
            q4U2TY0MLtgLDAPb0ffujVDe1fnSJsP4l4cl+FptDan+BiljIMfQCnHkcsk9/oo2
            6lDbcuX7SJXF72CZFmsqzZYrLb044rpIP+pZSiwAi9nhkQmjIKLm88MV0tx5Aria
            O7fdkqLv60B0t42zFFDlU9Ojo3GRhLDlX6Z9T2gNUlrjusUWWMRarGcarYGJwUz/
            fP2043yWF4KQB8O5G6lR/IVZCYa6h0JYI1vul/s9gdtrlmZF3wlrsOVP5dxUHNwJ
            eDMNu2S8ULXaxwe7OOndBADYkV15c+XUb3MEoopyXv8q7HDMliMmYTlmtS5j8E7S
            XgHnRZh2Up780w60dyzBMgZO1CmmQerGTSNm6I8CfhhNRpVKqAITCum4UxbwO7JX
            Dc1amzAkKk5x4PvlX8hYqwKBImmtHfJlGVqkQIwfxaLB/2U6YlJQWjqttQ12qtQ=
            =EIm4
            -----END PGP MESSAGE-----
          fp: B02D76EED45B9B5778A43B69CC35AD50960E16C2
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DGePB2r9HxYkSAQdAY3NtT4cnPx+umv30qbP6QkVmLxZXTitrpOIQ/A359CUw
            VtD5qbjn2Hr69NV55kr1pnyLbV3+7pJYg8FafpK68u8HdD69v/x/Vxs0+7KSgDZQ
            0l4BnSXEuqyK1L8fxOjbvM3//Df90J7gJKn1KxMAgjAeoSJqOEBXbFjWon4t6RAQ
            Rg15DUWY7aRVjaACNbDCDy6IBFX17iAM6CpnLiTbtuYKFuo0apOZhJQZTrQ2tMzN
            =rd9m
            -----END PGP MESSAGE-----
          fp: 5A3F5D11B86C085EAAC7F0B54136591338099DBA
        - created_at: "2026-06-13T00:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DrvgYWgvgiW4SAQdAHHVkNWDltmpK+E3yg9Cj8XA2FRzwJ+rY0Gk5SBj4mWcw
            1YMPAtrr+V4jbrOB6uGk8Dvtt/XjdHyiuGnJAs1qKbc5J7JfS4CwpLWvuauJ/m5B
            0l4BhG28IUFQOT8zjXDJZ01m/Ji+9FmFuyV6kzgF23CJeywejIVlOU3+PG9ni8BL
            RVCqxDGFejMwxOYMV9o66sldPjKikhn1rsQb4eK9DoXF9JYjoxPbJEjcTKZ/Q0Kh
            =NxSs
            -----END PGP MESSAGE-----
          fp: F75CA0B534439722B612D343FAB6BD4E290CA406
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
