---
- name: Create root directory config
  file:
      path: '{{ homelab_dest_folder }}'
      state: directory
      mode: '0755'

- name: Create directory structure for configs
  file:
      path: '{{ homelab_dest_folder }}/{{ item.path }}'
      state: directory
      mode: '0755'
      owner: docker-default
      group: docker-default
  with_filetree: '{{ config_src }}'
  when: item.state == 'directory'

- name: Template config files
  template:
      src: '{{ item.src }}'
      dest: '{{ homelab_dest_folder }}/{{ item.path }}'
      owner: docker-default
      group: docker-default
  with_filetree: '{{ config_src }}'
  when: item.state == 'file'
