---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.42.2.10156
            securityContext:
              fsGroup: 568
              runAsUser: 568
              runAsGroup: 568
              privileged: true
            env:
              TZ: America/Toronto

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        hosts:
          - host: "plex.${domain}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main

    service:
      main:
        controller: main
        ports:
          http:
            port: 32400

    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      transcode:
        enabled: true
        type: emptyDir
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/
        globalMounts:
          - path: /media
            readOnly: false
      quicksync:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
            readOnly: false
