---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  upgrade:
    force: true
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.40.5.8897-e5987a19d
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plex.${domain}"
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        primary: true
        ports:
          http:
            port: 32400
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${storage_host_ip}"
            path: /raid/network_share/media/
        mountPath: /media
      quicksync:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        mountPath: /dev/dri
    podSecurityContext:
      fsGroup: 568
      runAsUser: 568
      runAsGroup: 568
    securityContext:
      privileged: true
    env:
      TZ: America/Toronto
